### ISSUE TITLE
<script setup> is not working on production build [bug]

### ISSUE THREAD

**Issue by zizyzhang** [vuejs/docs-next#1010]
## My environment : 
- MacBook Pro, M1 chip
- Node Version: 15.14
- vue : 3.0.11

## How to repeat the bug:
1.  flowing the v3 guide to create a new project using `vue-cli`
2. change the App.vue file to <script setup> style
3. run `npm serve` : everything is fine
4. run `npm build` then `serve dist` : nothing is rendered

## Notes:
Same problem is found here : https://github.com/vuejs/vue-cli/issues/6282

**Comment by NataliaTepluhina** [comment]
I'm closing this issue on the docs repo because I can't find out how it's related to documentation. Also, we already have issues on Vue CLI and core repositories
