### ISSUE TITLE
I'm confused with .vue file along the help document systems

### ISSUE THREAD

**Issue by DawnEve** [vuejs/docs-next#1025]
As a new learner to vue, I'm confused with .vue file while I'm reading and coding demos along through the documents.

No where before mentioned how to use .vue file, when I encontered it, I don't know how to run the code now and after this chapter.
https://v3.vuejs.org/guide/composition-api-introduction.html#why-composition-api

I think here need some improvement, either add some example here, or give some helpful links.
Thank you.

**Comment by skirtles-code** [comment]
Agreed.

The page about `setup`, https://v3.vuejs.org/guide/composition-api-setup.html, does include a link explaining SFC syntax but that comes a page too late. A link isn't really ideal though, we need to move the explanation of SFCs so that it's before we first use them.

Related: #555, #847

**Comment by NataliaTepluhina** [comment]
I agree with the sentiment but closing an issue as it's already reported and we plan to refactor this chapter 👍🏻
