### ISSUE TITLE
cannot access props in setup with default defined

### ISSUE THREAD

**Issue by m4kz** [vuejs/docs-next#1049]
Hi

There is an issue while accessing props in setup that have defined a default value with function. as in the following code:

```
import { defineComponent } from "vue";

export default defineComponent({
  props: {
    propA: {
      type: Function,
      default: function () {
        return "Hola";
      },
    },
    propB: {
      type: Boolean,
      default: true,
    },
  },
  setup(props) {
    console.log(JSON.stringify(props)); //it prints ok
    props. //props not visible


    return {

    };
  },
});

```
![image](https://user-images.githubusercontent.com/5706828/117798074-028fb680-b251-11eb-927a-3b27cc9bd865.png)

but if i remove the default with function as in this code:

```
export default defineComponent({
  props: {
    propA: {
      type: String,
    },
    propB: {
      type: Boolean,
      default: true,
    },
  },
  setup(props) {
    console.log(JSON.stringify(props)); //it prints ok
    props.propB;


    return {

    };
  },
});
```

then they are accesible:
![image](https://user-images.githubusercontent.com/5706828/117798185-27842980-b251-11eb-9913-037f906f3768.png)

im using vue 3: `"vue": "^3.0.0"`

Thank you.

**Comment by skirtles-code** [comment]
Hi @m4kz.

This issues list is for reporting problems with the Vue 3 documentation. The problem you're having doesn't appear to be related to the documentation. My first impression is that it's a problem with whatever IDE or IDE plugin you're using.

If you have any further questions I suggest asking on [Vue Discord](https://chat.vuejs.org/).

Thanks.
