### ISSUE TITLE
Vue  failed to 'Auto-prefixing' ?

### ISSUE THREAD

**Issue by ttttttssssss** [vuejs/docs-next#1059]
https://v3.vuejs.org/guide/class-and-style.html#auto-prefixing
Vue will automatically detect and **add** appropriate prefixes to the applied styles .

expected
```
add prefixes to experimental or nonstandard CSS
```

DEMO

Chrome 80.0.3987.162

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://unpkg.com/vue@next"></script>

</head>

<body>
    <div id="app">
        <h1 :style="style">hello vue</h1>
    </div>
    <script>
        const app = Vue.createApp({
            data() {
                return {
                    style: {
                        transform: 'translate(10px)',
                        'border-image': 'none 100% 1 0 stretch'
                    }
                }
            }
        }).mount('#app')
    </script>
</body>

</html>
```
RESULTS
```
<div id="app" data-v-app=""><h1 style="transform: translate(10px); border-image: none 100% 1 0 / 1 / 0 stretch;">hello vue</h1></div>
```

**Comment by skirtles-code** [comment]
I believe this is working correctly.

The code to handle this is here:

https://github.com/vuejs/vue-next/blob/f7c54caeb1dac69a26b79c98409e9633a7fe4bd3/packages/runtime-dom/src/modules/style.ts#L67

Prefixes are only added where required. `transform` and `border-image` don't require them. Here's an example using `text-emphasis`, which currently needs a prefix in Chrome and Edge:

https://jsfiddle.net/skirtle/Lb5wqdzp/

I'll make an update to the docs to try to set expectations a bit better.
