### ISSUE TITLE
`setup`'s parameter `expose` is not documented

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/docs-next#1064]
Couldn't find `expose` anywhere in the document, please correct me if I'm mistaken.

Taken from https://github.com/vuejs/vue-next/blob/f7c54caeb1dac69a26b79c98409e9633a7fe4bd3/packages/runtime-core/src/component.ts#L179:

```ts
export declare interface SetupContext<E = EmitsOptions> {
  attrs: Data
  slots: Slots
  emit: EmitFn<E>
  expose: (exposed: Record<string, any>) => void
}
```

It's the savior for this type of issues: https://stackoverflow.com/q/67659374/7881859

**Comment by LiuQixuan** [comment]
expose used to expose variable in <script setup></script> like use return to expose variable in setup function .
This is an experimental syntax, please do not use it in a production environment, its api may change and cause incompatibility with future versions

**Comment by skirtles-code** [comment]
This is still at the RFC stage and is considered experimental:

https://github.com/vuejs/rfcs/pull/210

It is related to another experimental feature, `<script setup>`:

https://github.com/vuejs/rfcs/pull/227

In that scenario the context object is accessed using `useContext()`, allowing access to `attrs`, `slots`, `emit` and `expose`.

Experimental features are typically not included in the documentation as they are still subject to change.
