### ISSUE TITLE
`withKeys` is not documented

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/docs-next#1066]
![image](https://user-images.githubusercontent.com/28700378/119431895-fa9e3f00-bd45-11eb-91ef-8f8469b58ef7.png)

**Comment by skirtles-code** [comment]
I don't think `withKeys` is considered part of the public API. It's marked as `@private` in the code you referenced and as 'Internal' in `packages/runtime-dom/src/index.ts`.

**Comment by wenfangdu** [comment]
@skirtles-code Too bad, it's really helpful for use cases like this:

```jsx
<input
  v-model={password.value}
  type='password'
  onKeyup={withKeys(login, ['enter'])}
/>
```

Can we consider making it public? Given vue 3 is tree-shakeable, I think there's no obvious drawback to this.

**Comment by NataliaTepluhina** [comment]
@wenfangdu I believe the question about making it public should be raised in the core repo. We won't make changes to the documentation until it stays `@private` in the source code.

Closing this issue, please don't hesitate to open a proposal in the core one if you believe `withKeys` should be public.

**Comment by wenfangdu** [comment]
For reference: https://github.com/vuejs/vue-next/issues/3827

**Comment by marcelocra** [comment]
Hey there! Just stumbled upon this issue with the same problem.

Diving deeper, I noticed that the `withModifiers` is also marked as private, even though it is [documented]().

Should we not use it either?
