### ISSUE TITLE
Lifecycle Diagram:'createApp' and'mount' are overwritten, very ugly

### ISSUE THREAD

**Issue by cluyun** [vuejs/docs-next#1077]
![image](https://user-images.githubusercontent.com/33676184/120614525-e8c94400-c489-11eb-8fdf-49107a26617b.png)

**Comment by skirtles-code** [comment]
I think this is dependent on your platform. What OS and browser are you using?

Various other parts of the image are off too. The yellow asterisks are misplaced and there are some big gaps in the text in places where there shouldn't be gaps.

**Comment by cluyun** [comment]
> I think this is dependent on your platform. What OS and browser are you using?
> 
> Various other parts of the image are off too. The yellow asterisks are misplaced and there are some big gaps in the text in places where there shouldn't be gaps.

The problem has been fixed. thank you
不好意思，之前在忙没有回复您。我拉取了最新的仓库，看了下图片，确实问题已经得到修复！感谢。
