### ISSUE TITLE
Vue 3.0 Now when you run vm.fullName = 'John Doe', the setter will be invoked and vm.firstName and vm.lastName will be not updated accordingly.

### ISSUE THREAD

**Issue by linhuakun** [vuejs/docs-next#1085]
Vue 3 does not expose the data / computed and other attributes of Vue instances, and can not operate in the way Vue 2 does. There is a problem here.

**Comment by linhuakun** [comment]
![image](https://user-images.githubusercontent.com/72332066/121712941-df397f00-cb0e-11eb-826f-8ec4cf57c2fe.png)

**Comment by skirtles-code** [comment]
Thank you for reporting an issue but the code from that example seems to be working correctly for me:

https://jsfiddle.net/skirtle/6wn34ezv/

If you still believe there's a problem with the documentation, could you provide more information about how to reproduce it?
