### ISSUE TITLE
Vue3.x document  when you run vm.fullName = 'John Doe', set will be not updated

### ISSUE THREAD

**Issue by linhuakun** [vuejs/docs-next#1087]
![image](https://user-images.githubusercontent.com/72332066/121765069-f2823400-cb7a-11eb-9d8b-3e5ddcf7553a.png)
Vue 3 does not expose properties such as data/computed of Vue instances, and does not work the way Vue 2 does
![image](https://user-images.githubusercontent.com/72332066/121765125-56a4f800-cb7b-11eb-8c3e-5b4f483786d8.png)

**Comment by skirtles-code** [comment]
The thing you're calling `vm` in your code is not a component instance, it's the root component options. The component instance is returned by `mount`:

```js
const App = {
  template: "#app-id",
  // ...
};

const vm = Vue.createApp(App).mount("#app");
```

This is explained in an earlier section of the guide: https://v3.vuejs.org/guide/instance.html#component-instance-properties

I suggest using [Vue Land Discord](https://chat.vuejs.org/) for checking these kinds of problems before you report them here.
