### ISSUE TITLE
Customize search widget to match v2 docs website styles

### ISSUE THREAD

**Issue by NataliaTepluhina** [vuejs/docs-next#123]
Currently, all the search results are shown as a plain list. It would be nice to have something similar to v2 docs website where all results are divided onto categories

![Screenshot_3](https://user-images.githubusercontent.com/18719025/85945799-c27d5900-b948-11ea-9013-1622d0413e6e.png)

**Comment by marina-mosti** [comment]
@NataliaTepluhina what about the code example in `render-function.md` that shows `<!-- TODO: Add tagline -->`
Perhaps we should remove the `TODO` part of the comment for something else?

**Comment by NataliaTepluhina** [comment]
Closed as related PR was merged
