### ISSUE TITLE
Missing icons in style guide

### ISSUE THREAD

**Issue by bencodezen** [vuejs/docs-next#209]
<img width="810" alt="Screen Shot 2020-07-17 at 12 29 37 PM" src="https://user-images.githubusercontent.com/4836334/87809368-48464300-c829-11ea-8312-7625668c1db5.png">

**Comment by liulinboyi** [comment]
![image](https://user-images.githubusercontent.com/41336612/87846571-684a3500-c903-11ea-86e9-39357239ad2f.png)
![image](https://user-images.githubusercontent.com/41336612/87846599-9465b600-c903-11ea-945a-526be9f0befc.png)

Font-family name is error.
