### ISSUE TITLE
fix: Fixing typo at Async Component Migration Guide

### ISSUE THREAD

**Issue by manuelojeda** [vuejs/docs-next#213]
Found a typo at: https://v3.vuejs.org/guide/migration/async-components.html#introduction

![It says NextPAge](https://user-images.githubusercontent.com/22081875/87845095-5de75700-c881-11ea-9930-92592873926c.png)

Should be:
![Should be Next Page](https://user-images.githubusercontent.com/22081875/87845091-48722d00-c881-11ea-8da1-63e671c8057a.png)

**Comment by NataliaTepluhina** [comment]
@manuelojeda thank you so much for spotting it 🙇
