### ISSUE TITLE
Quotation mark issue in demo code 

### ISSUE THREAD

**Issue by wanmaoor** [vuejs/docs-next#217]
[Here is document link](https://v3.vuejs.org/guide/reactivity.html#how-vue-tracks-these-changes)

``` js
const dinner = {
  meal: ‘tacos’
}
```
The code above couldn't run, please modify it with

```js
const dinner = {
  meal: 'tacos'
}
```

**Comment by NataliaTepluhina** [comment]
@wanmaoor thank you for spotting this! Fixed 🎉
