### ISSUE TITLE
Possible misspelling in the 'Share Configurations Among Apps' section 

### ISSUE THREAD

**Issue by umutbozdag** [vuejs/docs-next#219]
I think there is a misspelling in [this](https://v3.vuejs.org/guide/migration/global-api.html#share-configurations-among-apps) section about function name. 

Since it is a factory function and returns the `app`, shouldn't it be like this?

```js
createMyApp().mount(Foo, '#foo')
createMyApp().mount(Bar, '#bar')
```

**Comment by NataliaTepluhina** [comment]
@umutbozdag thank you! It was misspelled indeed, fixed via https://github.com/vuejs/docs-next/commit/a0250c2c667a6d5cee7c1cca3a32d60461651c8c
