### ISSUE TITLE
Unused year variable in the section "Injection Reactivity"

### ISSUE THREAD

**Issue by sven-ahrens** [vuejs/docs-next#220]
## Issue

In that example, the const variable **book** is **used twice**, even for the ``provide('year', ...)`` function.

## Steps to reproduce

Go to: https://v3.vuejs.org/guide/composition-api-provide-inject.html#injection-reactivity

```
setup() {
  const book = reactive({
    title: 'Vue 3 Guide',
    author: 'Vue Team'
  })
  const year = ref('2020')

  provide('book', book)
  provide('year', book)
}
```

## What is expected?
```
  provide('book', book)
  provide('year', year)
```

## What is actually happening?

```
  provide('book', book)
  provide('year', book)
```

**Comment by NataliaTepluhina** [comment]
@sven-ahrens thank you! Fixed via https://github.com/vuejs/docs-next/commit/43c7e27549959783187a71a7ad67e0f46ab4cafb
