### ISSUE TITLE
Update Installation page with DevTools and Vite

### ISSUE THREAD

**Issue by NataliaTepluhina** [vuejs/docs-next#230]
We should update the installation page regarding DevTools availability and include Vite as a starting option
- [x] Add DevTools to the Installation page
- [x] Add Vite as a starting option to the Installation page
- [ ] Write an explanation on different builds similarly to https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds

**Comment by robokozo** [comment]
Would it be possible to add instructions to get it working with https://github.com/vuejs/vue-cli-plugin-vue-next ?

**Comment by NataliaTepluhina** [comment]
@robokozo yes, I believe so! I will add a brief installation instruction and will remove it when CLI is ready 👍🏻
