### ISSUE TITLE
Wrong variable referenced in Provide/Inject section

### ISSUE THREAD

**Issue by klausXR** [vuejs/docs-next#231]
The variable name from the provide object is named `user`, but the injected one is named `foo`
[link](https://v3.vuejs.org/guide/component-provide-inject.html#provide-inject)
![image](https://user-images.githubusercontent.com/35328918/87858707-81210d80-c938-11ea-888b-d00ddbdd700d.png)

**Comment by NataliaTepluhina** [comment]
@klausXR thank you so much for catching it! Fixed via https://github.com/vuejs/docs-next/commit/a1d118383e8bb5883c10d1f4504b094856e8bcf2
