### ISSUE TITLE
Need a path for /guide/ url

### ISSUE THREAD

**Issue by acidiney** [vuejs/docs-next#238]
You need to rename the introduction file to index, to allow the route /guide/ and thus allow the current documentation to follow to be new when you select the next in the select options.

I have already solved this, according to the PR #237

**Comment by bencodezen** [comment]
Thanks for opening an issue @acidiney. To give you some context, we are still considering whether to use a redirect rather than the `index.md` route of implementation. Appreciate you taking an initiative on this! 👍
