### ISSUE TITLE
Wrong link on Ref page (localhost:8080)

### ISSUE THREAD

**Issue by edimitchel** [vuejs/docs-next#240]
Going on https://v3.vuejs.org/api/refs-api.html#customref, the last link point to a localhost domain.
May be, elsewhere this typo exists..

Here the fix : https://github.com/edimitchel/docs-next/commit/885282f202238dcf79131b4588aa3233ecc996df

**Comment by bencodezen** [comment]
Good catch! Do you mind submitting a PR @edimitchel? Would love to give you credit for finding the issue and solving it!

**Comment by edimitchel** [comment]
Yes, I can do it now ! I create this issue because the PR template invites to do it ;)

**Comment by NataliaTepluhina** [comment]
Closing an issue as related PR was merged
