### ISSUE TITLE
Click the drop-down title, then click elsewhere on the page, the drop-down list always show.

### ISSUE THREAD

**Issue by liulinboyi** [vuejs/docs-next#244]
Click the drop-down title, then click elsewhere on the page, the drop-down list always show. when you click the drop-down title again, the drop-down list will disappear.
![nav](https://user-images.githubusercontent.com/41336612/87866339-16f97e80-c9b3-11ea-95ac-540db3fda7d1.gif)
I think it can be changed to this:
Click the drop-down title, then click elsewhere on the page, and the drop-down list disappears.

![navafter](https://user-images.githubusercontent.com/41336612/87866413-30e79100-c9b4-11ea-8a85-04ebc7f0e1b2.gif)

**Comment by NataliaTepluhina** [comment]
@liulinboyi thank you for reporting it! I believe it's worth open an issue on [VuePress repo](https://github.com/vuejs/vuepress) as we use it and I can spot the same behavior on [VueApollo](https://apollo.vuejs.org/) website (also built with VuePress). 🙏🏻 

Unfortunately, we can't fix it on our side, so I'm closing the issue
