### ISSUE TITLE
First example in introduction doesn't demonstrate reactivity

### ISSUE THREAD

**Issue by Aurelius333** [vuejs/docs-next#253]
In the very [first example](https://v3.vuejs.org/guide/introduction.html#declarative-rendering) in the new introduction, it says:

> The data and the DOM are now linked, and everything is now **reactive**. How do we know? Change the `message` property in the code snippet below to a different value and the rendered example will update accordingly:

However, I'm not sure that changing the code snippet in the CodePen really demonstrates reactivity, since that seems to just restart the CodePen with a different initial state. 

Those first examples in the v2 docs were helpful for me in understanding what reactivity means in Vue, so I wonder if it's worth changing the first and third examples to run directly on the page like in the v2 docs so that the app can be exposed to the console. As a reminder, the v2 docs said:

> The data and the DOM are now linked, and everything is now **reactive**. How do we know? Open your browser’s JavaScript console (right now, on this page) and set `app.message` to a different value. You should see the rendered example above update accordingly.

Thank you all for your hard work!

**Comment by NataliaTepluhina** [comment]
@Aurelius333 Thank you for the super valuable feedback! Unfortunately, it's not possible with VuePress (and it's also far from best practice) to attach the global property to `window` as we don't embed scripts directly to the page like Hexo did.

I totally understand and share the concern but I can't come with a good solution to resolve it with the current stack. We could create a component that exposes an input field (with `v-model` applied internally) and let user add a text there but this would require us to show `v-model` early and this breaks the user flow.

I am open to any ideas here 😅

**Comment by Aurelius333** [comment]
Here's my possible solution: <https://github.com/vuejs/docs-next/compare/master...Aurelius333:intro-reactivity-examples-without-codepen?expand=1>. I created components for the first and third examples in `src/.vuepress/components`, and I added `mounted` hooks that attach `this` to `window`:

```js
  mounted() {
    window.HelloVueVm = this
  }
```

In the example code on the page, I assigned the last line of the first example to `HelloVueVm`:

```js
const HelloVueVm = Vue.createApp(HelloVueApp).mount('#hello-vue')
```

That way, in both the code example and on the actual page, you can do `HelloVueVm.message = 'some other message'`.

There are some disadvantages to this approach:
1. Code duplication
2. The code in the example isn't exactly the same as the code that's actually used on the page. (Though it seems to me like they have the same behavior.)
3. As you said, it's probably bad practice to be attaching `this` to `window`.

I think it might be worth it to have the quick, easy example that you can run in the console, but I understand if it's not worth the tradeoff.

**Comment by CyberAP** [comment]
Mobile users don't have an easy access to browsers console, I think this should be considered as well. For me personally it is enough for the first example to be a simple input field and a text value synced with the field. That I think singlehandedly showcases what problems Vue solves.
