### ISSUE TITLE
NavLink dropdown menu doesn't close if you click on the NavLink

### ISSUE THREAD

**Issue by CyberAP** [vuejs/docs-next#259]
Steps to reproduce:

1. Hover over any NavLink, a dropdown should appear
2. Click on the NavLink itself
3. Move cursor out of the link to close the dropdown
4. Dropdown doesn't close

**Comment by NataliaTepluhina** [comment]
Duplicate of https://github.com/vuejs/docs-next/issues/244

I don't think this issue is specific to the documentation repository. Would you mind opening an issue on VuePress repo instead?
