### ISSUE TITLE
Ref could used with a function

### ISSUE THREAD

**Issue by edimitchel** [vuejs/docs-next#292]
Ref docs : https://v3.vuejs.org/api/special-attributes.html#ref

The attribute is a string in the docs, but we can use a function with as parameter the element ref.

```html
<input 
  :ref="(ref) => inputRef = ref"
/>
```
This is feasable ! May be, this could be explicited in the attribute type ?

**Comment by NataliaTepluhina** [comment]
Thank you @edimitchel! Fixed via https://github.com/vuejs/docs-next/commit/c233b25a05d2dc37b77eab8e702f9cfe88a14353
