### ISSUE TITLE
Small bug with a custom block on the installation page

### ISSUE THREAD

**Issue by joshgrib** [vuejs/docs-next#305]
On [the installation page](https://v3.vuejs.org/guide/installation.html#from-cdn-or-without-a-bundler) there is a custom block which is just "Note" which causes it to render like this

![](https://i.gyazo.com/719a60392b1059a6ec8a0ef85ad3e0dd.png)

I'm not sure if there is supposed to be a new `Note` custom block because I see that plugin being used, but I couldn't find any styles for it. Changing `:::Note` to `:::tip Note` results in:

![](https://i.gyazo.com/64768ef77ad9a636c5d1a57090dbc2e0.png)

**Comment by NataliaTepluhina** [comment]
@joshgrib thank you for reporting this! Fixed via https://github.com/vuejs/docs-next/commit/5e33c5b51462348d7d3b24505e54ec82f18c3180
