### ISSUE TITLE
Example missing: "Using template refs in Composition API"

### ISSUE THREAD

**Issue by sven-ahrens** [vuejs/docs-next#307]
I was reading the documentation about template refs: https://v3.vuejs.org/guide/component-template-refs.html

And I was curious how to access this with the composition API. There is a link which should redirect me to this topic but it doesn't exists.

It says:

> See also: Using template refs in Composition API

And when I click the link, the following URL opens: https://v3.vuejs.org/api/composition-api.html#template-refs

but there is no example for template refs. Maybe I'm missing it tho.

**Comment by sven-ahrens** [comment]
Probably it should redirect to this url here: https://v3.vuejs.org/guide/composition-api-template-refs.html#template-refs

**Comment by NataliaTepluhina** [comment]
@sven-ahrens thank you! Yes, this section was moved but the link didn't change.

Fixed via https://github.com/vuejs/docs-next/commit/5bc4f7c59e7e73f0800bac43912c88cfe37f11a8
