### ISSUE TITLE
How to participate in document translation? 

### ISSUE THREAD

**Issue by misitebao** [vuejs/docs-next#310]
At present, there is no Chinese version of the official website. Can I participate in the translation of the document?

**Comment by NataliaTepluhina** [comment]
@misitebao so far we don't have any translations for the v3 website as it's still under active development. We plan to have the same strategy that we had for v2, so I would recommend contacting the group that was handling Mandarin translation for Vue 2: https://github.com/vuejs/cn.vuejs.org

**Comment by misitebao** [comment]
OK, thank you.
