### ISSUE TITLE
Decide on i18n strategy

### ISSUE THREAD

**Issue by NataliaTepluhina** [vuejs/docs-next#32]
We need to decide on how do we want to handle translations. I think for now it's really too much work to move them to separate folders on docs VuePress site so maybe it's a good idea to leave them as separate repos? Let's discuss

**Comment by beetaa** [comment]
Hi Natalia, how about the translation plan? If I want to tranlate, how can I begin with vue3's new doc? thanks. @NataliaTepluhina

**Comment by CyberAP** [comment]
The questions I have for i18n are:

1. What is the user experience when a page is partially or not translated at all?
2. Will the new i18n be able to handle switching language and preserving the same page for the user?
3. How refactoring documentation will affect translators?
4. What is the strategy for translators to keep up with the latest changes in English documentation?
5. What is the quality control policy on community translations?

**Comment by bencodezen** [comment]
Thanks for everyone's input! At this time we're still trying to figure out how to best approach this given current translation efforts in v2. 

For more information on getting involved with the translation community, check out https://github.com/vuejs/vuejs.org/issues/2015
