### ISSUE TITLE
Codepen problem with GreenSock licensing

### ISSUE THREAD

**Issue by amrnn90** [vuejs/docs-next#322]
Some Codepen embeds give me the following error:

![Capture](https://user-images.githubusercontent.com/38134195/88158735-13653200-cc15-11ea-91cf-7291767c1fb0.PNG)

**Comment by amrnn90** [comment]
Issue was related to me using Brave browser, disabling its privacy protection for the page solved the issue...feel free to close this.

**Comment by NataliaTepluhina** [comment]
@amrnn90 thank you for reporting this! I'll close the issue for now but it's great to know we can have issues with privacy protection, would be useful if we have similar reports on the same issue 👍🏻
