### ISSUE TITLE
Broken link on the introduction page

### ISSUE THREAD

**Issue by sven-ahrens** [vuejs/docs-next#323]
## Issue

When clicking on the following link: https://v3.vuejs.org/guide/todo:comparison.html it shows an 404 error

> There's nothing here.

## how to reproduce

Visit: https://v3.vuejs.org/guide/introduction.html#what-is-vue-js

You'll see this text:

> If you are an experienced frontend developer and want to know how Vue compares to other libraries/frameworks, check out the Comparison with Other Frameworks.

Click on **Comparison with Other Frameworks**

**Comment by NataliaTepluhina** [comment]
Thank you for reporting this @sven-ahrens! It's an intentional TODO link, we will add a link to `Comparison` section when it's ready
