### ISSUE TITLE
Broken link on the template syntax page

### ISSUE THREAD

**Issue by sven-ahrens** [vuejs/docs-next#324]
# Issue

The following link has syntax errors: todo:https://github.com/vuejs/vue/blob/v2.6.10/src/core/instance/proxy.js#L9 and will result in an "page not found" error

# how to reproduce

Visit: https://v3.vuejs.org/guide/template-syntax.html#shorthands

You'll see this text:

> Template expressions are sandboxed and only have access to a whitelist of globals such as Math and Date. You should not attempt to access user defined globals in template expressions.

Click on **whitelist of globals**

**Comment by sven-ahrens** [comment]
Oh, it doesn't even open up when clicking on it. You'll have to right click it and try to open it up then

**Comment by NataliaTepluhina** [comment]
Thank you for reporting this! Fixed via https://github.com/vuejs/docs-next/commit/885750220b837c738e2cfbab386e669d6012a2f8
