### ISSUE TITLE
Non todo link broken in Components Basics

### ISSUE THREAD

**Issue by sven-ahrens** [vuejs/docs-next#325]
## Issue
**Dynamic & Async Components** link broken at the end of the page.

## how to reproduce

Visit: https://v3.vuejs.org/guide/component-basics.html#dom-template-parsing-caveats

Search for 

> Once you feel comfortable with the knowledge you've just digested, we recommend coming back to read the full guide on Dynamic & Async Components, as well as the other pages in the Components In-Depth section of the sidebar.

and click on the following link: (**Dynamic & Async Components**): https://v3.vuejs.org/guide/components-dynamic-async

## What is expected
Should open up: https://v3.vuejs.org/guide/component-dynamic-async.html

## What is does
It opens: https://v3.vuejs.org/guide/components-dynamic-async which results in 404

**Comment by NataliaTepluhina** [comment]
@sven-ahrens thank you for reporting this! Fixed on `master`
