### ISSUE TITLE
Vue Testing Library Recommendation

### ISSUE THREAD

**Issue by 185driver** [vuejs/docs-next#326]
From the [docs](https://v3.vuejs.org/guide/testing.html#vue-test-utils):

>Vue Test Utils is the low-level component testing library that was written to provide users access to Vue specific APIs. While it is officially maintained, we recommend most users use Vue Testing Library, which is an abstraction over Vue Test Utils.

This new statement recommending Vue Testing Library **over** Vue Test Utils as a norm for users seems surprising. Does the core-team indeed recommend the former over the latter?  If so, is this also an indication of changes coming to the `@vue/cli-plugin-unit-jest` plugin (which does not currently use Vue Testing Library), and/or of a planned phase out of Vue Test Utils? 

A documented preference by the Vue team away from direct use of its own official tool seems noteworthy, so I wanted to ask.

**Comment by NataliaTepluhina** [comment]
@185driver thank you for voicing this! We've created a pull request to change the explanation: https://github.com/vuejs/docs-next/pull/330
