### ISSUE TITLE
Delete the redundant '</div>' in the example

### ISSUE THREAD

**Issue by gmaso** [vuejs/docs-next#329]
In the example code of [https://v3.vuejs.org/guide/a11y-semantics.html#hiding-content](https://v3.vuejs.org/guide/a11y-semantics.html#hiding-content), there '\<\/div\>' on line 4 is redundant:
```javascript
<form role="search">
  <label for="search" class="hidden-visually">Search: </label>
  <input type="text" name="search" id="search" v-model="search" />
    </div>
    <button type="submit">Search</button>
</form>
```

**Comment by NataliaTepluhina** [comment]
@gmaso thank you for reporting this! Fixed 🙇🏻‍♀️
