### ISSUE TITLE
Wrong example component name (ChildComponent vs MyBook)

### ISSUE THREAD

**Issue by JoeSchr** [vuejs/docs-next#332]
```
<ChildComponent v-model="pageTitle" />

<!-- would be shorthand for: -->

<MyBook :modelValue="pageTitle" @update:modelValue="pageTitle = $event" />
// from // https://github.com/vuejs/docs-next/edit/master/src/guide/migration/v-model.md:99
```

Because in every other example the component is named `ChildComponent`, I deduce that it should be here as well. ;)

Probably a search and replace mishap. Otherwise I enjoyed reading this, short and to the point!

**Comment by NataliaTepluhina** [comment]
@JoeSchr thank you! There is always one component where you fail to replace 😅 

Fixed via https://github.com/vuejs/docs-next/commit/c8f41824fbfc73c54b4b7015e21cdcaa39848dc1
