### ISSUE TITLE
[vite] Error: a local installation of `vue` is detected but no matching `@vue/compiler-sfc` is found. Make sure to install both and use the same version.

### ISSUE THREAD

**Issue by nasirDoe** [vuejs/docs-next#334]
![error-vite](https://user-images.githubusercontent.com/16643567/88352179-1da53e80-cd83-11ea-93a3-0277c3443da3.png)
When i was upgraded to new version, i have some errors when i `yarn dev`. Any help ?

**Comment by NataliaTepluhina** [comment]
@nasirDoe thank you for reporting this! Could you please open the same issue on the Vite repository for visibility?

**Comment by nasirDoe** [comment]
@NataliaTepluhina thank's for reply my answer, btw i was found the problem for this issue. the problem is when i upgrading dependencies, my vue 3 was replaced to vue 2.

**Comment by marina-mosti** [comment]
@nasirDoe thanks for the update, closing the issue now :)
