### ISSUE TITLE
Migration guide: document changes in mounting point

### ISSUE THREAD

**Issue by leopiccionia** [vuejs/docs-next#335]
In Vue 3.0, there's a subtle breaking change in app mounting ([see RFC](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0009-global-api-change.md#mounting-behavior-difference-from-2x)).

In Vue 2.x, app element's `outerHTML` is replaced (and eventually compiled to a template, if root component has no `template`/`render`). Vue 3.x now uses app element's `innerHTML`, instead.

This change usually is harmless, but code that expects previous behavior may break (e.g. https://github.com/vuejs/vue-next/issues/1642 and https://github.com/vuejs/vue-next/issues/1696).

I couldn't find any mention to this behavior change in migration guide. I'm sorry if this is not the case.

**Comment by NataliaTepluhina** [comment]
@leopiccionia thank you for mentioning this! I believe you're correct and we should mention this in the migration guide

**Comment by skirtles-code** [comment]
The lifecycle diagram will also need updating:

![Lifecycle diagram](https://user-images.githubusercontent.com/65301168/89104868-62307a00-d414-11ea-9907-5004668d724c.png)

I believe the change from `outerHTML` to `innerHTML` is a consequence of a larger change to how the mounting element is used. In Vue 2 the element was replaced, whereas in Vue 3 it is used as a container. This impacts all Vue applications, not just those using in-DOM templates.

For example, if you have an SFC with a template like this:

```html
<template>
  <div id="app">
    ... Content ...
  </div>
</template>
```

and you mount it to an element like this:

```html
<div id="app"></div>
```

the resulting DOM will be:

```html
<div id="app" data-v-app>
  <div id="app">
    ... Content ...
  </div>
</div>
```

Note that there are now two elements with `id="app"`, whereas in Vue 2 there would only be one.
