### ISSUE TITLE
 The doc at the bottom of the chapter 'Form Input Bindings' shows an error

### ISSUE THREAD

**Issue by ibwei** [vuejs/docs-next#337]
as the picture shows:
![image](https://user-images.githubusercontent.com/25237993/88455226-30fcfa80-cea6-11ea-84a7-6097e4f9cd73.png)

**Comment by NataliaTepluhina** [comment]
@ibwei thanks for reporting this! Unfortunately, I can't reproduce the issue, could you please clean the browser cache for this page or try it incognito mode?

**Comment by ibwei** [comment]
I can't reproduce this problem,either.when I refresh this page,it works well, it may be my own mistake.so I will close it later.
