### ISSUE TITLE
Highlight `key` prop in the loops introduction section

### ISSUE THREAD

**Issue by onmyflow** [vuejs/docs-next#338]
Having a missing `key` in for loops can sometimes result in nasty to debug bugs. 
Currently there is only one small inline comment in a code section mentioning the `key` prop in the loops documentation and it only says that the `key` prop will be explained _later_.
I think it's very important to stress the importance the `key` prop has when using `for` loops on dynamic data.
There has already been confusion in the vue-next issue section, because it's not explained clearly when reading the docs in the context of `for` loops.

**Comment by NataliaTepluhina** [comment]
@onmyflow as far as I remember, for Vue 3 `key` property will be only _required_ on `v-for` loops on components. On native HTML elements, it's _recommended_ if you have a unique property but not _required_

Could you please post a link to the mentioned confusion?

**Comment by NataliaTepluhina** [comment]
Closing as a stale one
