### ISSUE TITLE
V-model Modifiers Confusion

### ISSUE THREAD

**Issue by joezimdelta** [vuejs/docs-next#342]
https://v3.vuejs.org/guide/component-custom-events.html#handling-v-model-modifiers says 

> In 2.x, we have hard-coded support for modifiers like .trim on component v-model. However, it would be more useful if the component can support custom modifiers. In 3.x, modifiers added to a component v-model will be provided to the component via the modelModifiers prop:

It then shows a few examples of how modifiers get passed down and such, but sometimes they implement the capitalize modifier and sometimes they don't. Is capitalize a built-in modifier? Are there any built-in modifiers still? The language and examples give no way to determine one way or the other.

**Comment by NataliaTepluhina** [comment]
@joezimdelta thank you for reporting this! Makes sense to me, we will add a note about existing built-in modifiers as well as specify that you can extend this list with custom modifiers 👍🏻

**Comment by NataliaTepluhina** [comment]
Closing an issue as related PR was merged
