### ISSUE TITLE
Unterminated string in lifecycle hooks example

### ISSUE THREAD

**Issue by smoooty** [vuejs/docs-next#346]
The console.log in the onMounted example code at the bottom of the page is missing a closing quote (after ` mounted!`), https://v3.vuejs.org/guide/composition-api-lifecycle-hooks.html.

It should be this:
```
// MyBook.vue

export default {
  setup() {
    // mounted
    onMounted(() => {
      console.log('Component is mounted!')
    })
  }
}
```

**Comment by NataliaTepluhina** [comment]
Closing, as a fix PR was merged

**Comment by smoooty** [comment]
@marina-mosti in the future would it be preferable to open a PR with the fix myself? I wasn't sure the best course of action since the docs are still a work in progress.

**Comment by bencodezen** [comment]
@smoooty Opening an issue was definitely the right thing to do. Thanks @smoooty!
