### ISSUE TITLE
Provide better experience for translation audit

### ISSUE THREAD

**Issue by bencodezen** [vuejs/docs-next#351]
Purpose: It should be easy for people to know what's active and what's up to date

**Comment by bencodezen** [comment]
Currently exploring CrowdIn as a possible solution.

But a MVP option would be to have an official list of all translations and repos with their last updated date to make it obvious to people.

**Comment by NataliaTepluhina** [comment]
Closing this, as now we have https://v3.vuejs.org/guide/contributing/translations.html#community-translations
