### ISSUE TITLE
Search page

### ISSUE THREAD

**Issue by NoelDeMartin** [vuejs/docs-next#352]
In v2 there was a separate search page at `/search` in order to have a url to run searches. For example: https://vuejs.org/v2/search/?q=v%2Dmodel

I implemented that in [this PR](https://github.com/vuejs/vuejs.org/pull/1488), so you can take a look there for the motivations and discussion.

Would it make sense to do the same here? Would it make more sense to implement this feature in VuePress instead?

**Comment by NataliaTepluhina** [comment]
@NoelDeMartin it would be great to have the same page for new docs! Regarding 'where to implement' question: I believe it would be beneficial for VuePress as well but if you think it would be faster/easier to add it to docs website only - let's implement it here first.

You also reminded me that I need to apply for Algolia DocSearch token 😅

**Comment by bencodezen** [comment]
@NoelDeMartin VuePress comes with a built-in search functionality, so I wonder if it makes sense to see if there's a way you can leverage it to build the search page. That said, if VuePress search functionality could use some improvement, then I think we could use your help on updating the VuePress library itself so a lot more people can benefit from your ideas!

**Comment by NoelDeMartin** [comment]
Hi @bencodezen. I've been looking into the [@vuepress/plugin-search](https://vuepress.vuejs.org/plugin/official/plugin-search.html#install) plugin and I'll probably make a PR to add it there afterwards.

But the docs at the moment are build using VuePress `1.3`, and the latest version is `1.5`. So I think it's still a good idea to add it here first. I'm not sure if the maintainers would accept a PR upgrading the VuePress dependency, and I'd also have to wait until a version with the search page is released.

If I create a PR here first, it's more likely that it gets merged before the official release of Vue 3 :).
