### ISSUE TITLE
v2 + v3 Docs Maintenance Strategy

### ISSUE THREAD

**Issue by bencodezen** [vuejs/docs-next#354]
## Background

Currently all of the v2 docs officially live in the `vuejs.org` repo under the `vuejs.org/v2` sub folder.

Given that v3 lives in the current `docs-next` repo under the `v3.vuejs.org` path, which is inconsistent from the current url structure, we need to determine a standard going forward.

## Proposal

1. Keep `v2` and `v3` docs in separate repos
1. Rename `vuejs.org` repo name to `v2.vuejs.org` (but do not change the URLs)
1. Rename `docs-next` repo name to `v3.vuejs.org`
1. Publish v3 docs to `vuejs.org/v3` to keep consistency with the current url structure
1. Ensure version switching between v2 and v3 is a smooth experience

**Updated:** _Remove idea to rename `v3` repo to `vuejs.org` due to breaking automatic redirection_

## Rationale

While there are advantages to having `v2` and `v3` existing in the same repo, this would actually require a lot of effort to migrate this properly and would have little to no impact to the end user. Given that most of the efforts going forward should be focused on improving `v3`, the cost of having two separate repos is acceptable given the changes to `v2` should be minimal and primarily maintenance (rather than significant enhancements).

In the event that we require infrastructure changes, such as moving from Hexo to Vue/VitePress, we shall overcome that obstacle at the time. But otherwise, trying to consolidate into a single repo is most likely a pre-optimization at this point that would not be a good use of contributors' time and energy.

## Feedback

What do you think @NataliaTepluhina @sdras @phanan @yyx990803?

**Comment by phanan** [comment]
Sounds good! I have one concern, though: Can 2. and 3. co-exist? AFAIK after 2., `vuejs.org` repo will be redirected to `v2.vuejs.org`. I'm not sure how 3. would work—will GitHub allow that, what'd happen to redirections etc.

**Comment by bencodezen** [comment]
@phanan Oof that's a great point. I'll just did a quick search and it looks like you're concern is correct. I've amended the original proposal.

**Comment by NataliaTepluhina** [comment]
Closing this as we've decided that `v3` will eventually become `vuejs.org`
