### ISSUE TITLE
Broken example in the vue docs.

### ISSUE THREAD

**Issue by EmmyMay** [vuejs/docs-next#357]
![image](https://user-images.githubusercontent.com/31524469/88948959-7f394180-d28a-11ea-8779-2dbfed2fabd0.png)

It is the part on Reactivity.

https://v3.vuejs.org/guide/reactivity.html#what-is-reactivity

**Comment by NataliaTepluhina** [comment]
I believe there is an issue with Brave browser: https://github.com/vuejs/docs-next/issues/322#issuecomment-662348625
