### ISSUE TITLE
Add to V2 migration docs about change in transition class names

### ISSUE THREAD

**Issue by BenRutlandWeb** [vuejs/docs-next#359]
### What problem does this feature solve?
I spent hours trying to debug transitions not working. The reason being `.v-enter`/`.v-leave` has changed to `.v-enter-from`/`.v-leave-from`.

I'm aware that the docs are a work in progress but I'd hate for early adopters to waste as much time as I just did!

This is possible not the correct place for this comment but I don't know where else it should go.

Great work on the new version BTW!

### What does the proposed API look like?
A paragraph on the v3 docs site, in the migration from v2 section, detailing the change in class names.

**Comment by bencodezen** [comment]
Related to #138

**Comment by NataliaTepluhina** [comment]
@BenRutlandWeb @bencodezen we actually have this paragraph on migration guide:

<img width="779" alt="Screenshot 2020-08-02 at 13 00 25" src="https://user-images.githubusercontent.com/18719025/89120583-34a10a80-d4c0-11ea-9d34-58d24627060b.png">

(also, API docs were already updated with correct class names).

I agree we'd need to have a dedicated section on this though 😅

**Comment by BenRutlandWeb** [comment]
🤦 That's easy to miss!

**Comment by bencodezen** [comment]
@BenRutlandWeb Totally understandable. We hope to have an official section in the Migration Guide on transitions soon!

**Comment by bencodezen** [comment]
We now have a guide thanks to @sdras! 

https://v3.vuejs.org/guide/migration/transition.html#overview
