### ISSUE TITLE
FAQ - Where should I start leads to migration guide from vue 1 to 2

### ISSUE THREAD

**Issue by bastiW** [vuejs/docs-next#360]
https://v3.vuejs.org/guide/migration/introduction.html#where-should-i-start-in-a-migration

The **Where should I start in a migration?** paragraph links to the https://github.com/vuejs/vue-migration-helper but the migration helper was made for upgrading from Vue 1.x to 2.0

**Comment by NataliaTepluhina** [comment]
The migration helper is not ready for now. As soon as it is, we will replace the link with an actual helper.

**Comment by NataliaTepluhina** [comment]
I removed a link there for now to prevent confusion 👍🏻
