### ISSUE TITLE
typo in reactive fundamentals section

### ISSUE THREAD

**Issue by Recks11** [vuejs/docs-next#361]
There is a typo in the second paragraph of this section https://v3.vuejs.org/guide/reactivity-fundamentals.html#destructuring-reactive-state

it says:
>Unfortunately, with such a destructuring the reactivity for both properties would be lost. For such case, we need to convert our reactive object to a set of refs. These refs will retaining the reactive connection to the source object:

and should/can be re-written as 
>Unfortunately, with such a destructuring the reactivity for both properties would be lost. For such a case, we need to convert our reactive object to a set of refs. These refs will retain the reactive connection to the source object:

**Comment by NataliaTepluhina** [comment]
@Recks11 thank you for reporting this! Fixed via https://github.com/vuejs/docs-next/commit/7662f5fd98c7e0c167212f4d935fa86153fde82b
