### ISSUE TITLE
Slots syntax in slots-unification is wrong

### ISSUE THREAD

**Issue by cathrinevaage** [vuejs/docs-next#366]
In [guide/migration/slots-unification](https://github.com/vuejs/docs-next/blob/master/src/guide/migration/slots-unification.md#3x-syntax), the syntax for passing slots to a component is incorrect.
RawSlots is not part of props, the second parameter in the used h overload, but part of third parameter children.
The syntax is correctly documented elsewhere: [guide/render-function](https://github.com/vuejs/docs-next/blob/master/src/guide/render-function.md#slots).

Suggested edit:
~~~patch
## 3.x Syntax

- In 3.x, render functions will have a `slots` option where they can be defined instead.
+ In 3.x, render functions can take an object of `slots` as the `children` parameter instead.

```js
// 3.x Syntax
- h(LayoutComponent, {
-   slots: {
-     header: () => h('div', this.header),
-     content: () => h('div', this.content)
-   }
+ h(LayoutComponent, {}, {
+   header: () => h('div', this.header),
+   content: () => h('div', this.content)
+ })
```
~~~

**Comment by Aferz** [comment]
https://github.com/vuejs/docs-next/pull/365

We overlapped. @maintainers, feel free to close the PR if needed.

**Comment by NataliaTepluhina** [comment]
@cathrinevaage and @Aferz thank you both for the report and suggested change! 🙇🏻‍♀️
