### ISSUE TITLE
Migration guide section about v-if key

### ISSUE THREAD

**Issue by Aurelius333** [vuejs/docs-next#379]
**Edit**: It seems like the behavior has changed on the master branch since I posted this yesterday, so the following description is out of date. I think it's still a breaking change, so the migration guide might still need a section on this. However, it might be good to wait a little bit before working on that, since it seems possible that the behavior could change again before the next release.

***

I can't find anything about this in the migration guide, but it seems to be a breaking change.

### Vue 2
In v2, it was common to use `key`s on `v-if`, `v-else`, and `v-else-if`. For example:
```vue
<h1 v-if="cond" key="a">A</h1>
<h2 v-else key="b">B</h2>
```

### Vue 3
In v3, this produces an compiler error because `key`s are **automatically generated** on `v-if`, `v-else`, and `v-else-if` nodes. These keys can be removed:
```vue
<h1 v-if="cond">A</h1>
<h2 v-else>B</h2>
```

### Vue 2
In v2, a `<template>` could not have a `key`, so when using a `<template v-for="...">` with a child `v-if`/`v-else`, you would place the `key` on both of the children:
```vue
<template v-for="thing in list">
  <h1 v-if="cond" :key="thing.id">A</h1>
  <h2 v-else :key="thing.id">B</h2>
</template>
```

### Vue 3
In v3, the previous example causes the `v-if` to not work properly, and it produces an error message. Because of Fragments, we can now put the `key` on the `<template>` directly:
```vue
<template v-for="thing in list" :key="thing.id">
  <h1 v-if="cond">A</h1>
  <h2 v-else>B</h2>
</template>
```

## Error message
This is the [new error message](https://github.com/vuejs/vue-next/blob/11ed2103919af46b5d9f573d3fad749ca7eb73f5/packages/compiler-core/src/errors.ts#L139-L142) for this problem in the master branch of vue-next. (This new message isn't released into a new version yet.)
> `v-if branches must use compiler generated keys. In many cases, you can simply remove this key. If this tag is inside of a <template v-for="...">, then you can move the key up to the parent <template>.`

## References
* https://github.com/vuejs/vue-next/issues/1734#issuecomment-665745971
* https://github.com/vuejs/vue-next/issues/1712#issuecomment-665206103

**Comment by NataliaTepluhina** [comment]
@Aurelius333 thank you for reporting this! I was writing `Conditional rendering` guide around this change indeed (so no `key`s there) but I haven't realized that v2 code with `v-if` + `key` would result in compiler error. Let's wait for the next release and then add this to migration guide

**Comment by Aurelius333** [comment]
In case it's helpful, here's my understanding of how it works as of the latest release.

As of v3.0.0-rc.6, it seems like it’s okay to provide explicit keys on `v-if`/`v-else`/`v-else-if` nodes, **as long as the keys are always different in different branches**. So "Example A" above is no longer a problem and doesn't need to be changed when upgrading to Vue 3. 

It seems like there are two breaking changes involved here. These could be two different sections in the migration guide, or maybe they could be combined into one section about changes to `key` usage. My "Example B" in the issue description is a combination of both of these breaking changes.
#### Change 1: `v-if`/`v-else`/`v-else-if` branches must use unique `key`s if `key`s are provided (but these `key` aren't necessary)
```vue
<div v-if="cond" :key="3">Yes</div>
<div v-else :key="3">No</div>
```
We can probably just recommend removing the `key`s in this case, since the compiler can now generate them for you. 

#### Change 2: `<template v-for>` `key` should be placed on the `<template>` tag.
Vue 2:
```vue
<template v-for="thing in list">
  <div :key="thing.id">...</div>
</template>
```
Vue 3:
```vue
<template v-for="thing in list" :key="thing.id">
  <div>...</div>
</template>
```

**Comment by NataliaTepluhina** [comment]
@Aurelius333 would you mind creating a pull request with these changes or would you prefer me to create it? 😅

**Comment by Aurelius333** [comment]
@NataliaTepluhina I'd be happy to create a pull request.
