### ISSUE TITLE
Add Mobile section to the docs

### ISSUE THREAD

**Issue by bencodezen** [vuejs/docs-next#386]
Given that mobile solutions are a popular request, it would be good to provide some guidance in this regard.

Things that come to mind include:

- NativeScript
- Capacitor
- Vue Native

**Comment by mhartington** [comment]
👋 Happy to contribute something for the capacitor content.

**Comment by mhartington** [comment]
I had some time and put together something like this.

![Screen Shot 2020-08-07 at 12 33 14 PM](https://user-images.githubusercontent.com/2835826/89667460-2bda7b00-d8aa-11ea-8a02-de64b0cbcefc.png)


A simple page for listing various solutions, their description, and linking out to other resources about them. Any thoughts on this?

**Comment by bencodezen** [comment]
@mhartington Looks like a great start! Thanks for getting this to us 👍
