### ISSUE TITLE
Provide / Inject: Use readonly

### ISSUE THREAD

**Issue by michaelzangl** [vuejs/docs-next#391]
In https://v3.vuejs.org/guide/composition-api-provide-inject.html

This is the current example for allowing components in which the object is injected to change the object.

```js
  const book = reactive({
    title: 'Vue 3 Guide',
    author: 'Vue Team'
  })

  function changeBookName() {
    book.title = 'Vue 3 Advanced Guide'
  }

  provide('book', book)
  provide('changeBookName', changeBookName)
```

I believe that best practice would be to mark the book as readonly and force the use of the setter that way:

```js
  const book = reactive({
    title: 'Vue 3 Guide',
    author: 'Vue Team'
  })

  function changeBookName() {
    book.title = 'Vue 3 Advanced Guide'
  }

  // NEW
  // readonly prevents direct mutation of book  and forces the use of the changeBookName function.
  provide('book', readonly(book))
  provide('changeBookName', changeBookName)
```

(and btw, this warning should best be placed in the normal [provide/inject](https://v3.vuejs.org/guide/component-provide-inject.html#working-with-reactivity) guide)

**Comment by NataliaTepluhina** [comment]
@michaelzangl thank you for discussing this! I would say that we should have both examples - with and without `readonly` (the latter one as a good example for warning). We can even make it recommended but we still should show that this is not a _requirement_

cc @bencodezen
