### ISSUE TITLE
v3.vuejs.org guide on destructuring slot has typo

### ISSUE THREAD

**Issue by ferry77** [vuejs/docs-next#392]
Hi, I believe this has typo mistake, may I made a PR to fix? Thank you.

> 
> You can even define fallbacks, to be used in case a slot prop is undefined:
> 
> ```
> <todo-list v-slot="{ item = 'Placeholder' }">
>   <i class="fas fa-check"></i>
>   <span class="green">{{ todo }}<span>
> </todo-list>
> ```
> 

It should says {{ item }} instead of {{ todo }}

**Comment by bencodezen** [comment]
@ferry77 Thanks you for asking. Please feel free to issue a PR for this!

**Comment by ferry77** [comment]
Thanks @bencodezen I have submitted a PR :)
