### ISSUE TITLE
v3.vuejs.org guide on Composition API Introduction has typo

### ISSUE THREAD

**Issue by ferry77** [vuejs/docs-next#393]
Hi, I believe this has typo mistake, may I make PR to fix this? Thanks

`methods: {

    getUserRepositories () {
      // using `this.user` to fetch user repositories
    }, // 2

    updateFilters () { ... }, // 3
  },`

**getUserRepositories** should be responsibility no#1

**Comment by ferry77** [comment]
as in 
`getUserRepositories () {
...
}, // 1
`

**Comment by bencodezen** [comment]
@ferry77 Just reviewed this too. Feel free to issue a PR as well. Thanks again for asking!
