### ISSUE TITLE
Improve clarity on using Symbol with provide / inject

### ISSUE THREAD

**Issue by vvanpo** [vuejs/docs-next#398]
The API docs for `provide / inject` (https://github.com/vuejs/docs-next/blob/master/src/api/options-composition.md#provide--inject) describes:

> You can use ES2015 Symbols as keys in this object, but only in environments that natively support Symbol and Reflect.ownKeys.

Since most users are likely using Babel+`core-js` or Typescript, `Symbol` is likely to be polyfilled. The emphasis of "natively support" in this sentence makes it unclear whether polyfills for these features in IE11 are sufficient for using them in `provide / inject`, or whether there is some specific reason that polyfills are not enough. If `import 'core-js';` is all that's needed to make Symbols work, can we remove the word "natively" (or otherwise say "have native or polyfilled support for")?

**Comment by bencodezen** [comment]
Thanks for the feedback @vvanpo! I'm checking with the team to make sure we clarify how this is defined and will get back to you once I get an answer!

**Comment by NataliaTepluhina** [comment]
@vvanpo currently, the current build of Vue 3 doesn't support IE11 and there will be a specific compatibility build for IE11 users. Would it make sense to say that for default build Symbol still has a native support?

**Comment by vvanpo** [comment]
@NataliaTepluhina right, so it will only require clarification once there is an IE11-compatible build. So for the current build, it likely doesn't need to make any mention of compatibility at all, since I'm assuming that all the environments Vue 3 currently supports also support `Symbol`.

I should note that the old v2 documentation for `provide`/`inject` contains the exact same sentence, though, so it looks like it was just copy-pasted: https://vuejs.org/v2/api/#provide-inject

**Comment by NataliaTepluhina** [comment]
I'm closing this one as compatibility build will most likely have it's own documentation
