### ISSUE TITLE
Arrays in $refs

### ISSUE THREAD

**Issue by skirtles-code** [vuejs/docs-next#400]
In Vue 2, if a `ref` attribute was used inside a `v-for` it would result in an array inside `$refs`.

However, this is not currently true in Vue 3 rc.5. This appears to be by design, see:

https://github.com/vuejs/vue-next/issues/1166

That issue mentions the possibility of an RFC but as far as I'm aware that hasn't happened. I'm unclear what the current plan is regarding backwards compatibility with Vue 2 for this feature.

If the plan is to abandon the use of `$refs` arrays within `v-for` then this should be mentioned in the migration guide. There are also various references to the old behaviour within the current documentation.

On a related note, it's also unclear what the expectation is with regards to using `ref` inside a scoped slot. Scoped slots have a similar problem to `v-for` in that they can create multiple nodes with the same `ref`. I don't think [the example](https://v3.vuejs.org/guide/composition-api-template-refs.html#usage-inside-v-for) of using a `ref` function with `v-for` would work with a scoped slot as it relies on `onBeforeUpdate` running on the parent. It would be good to get something on this topic somewhere in the documentation, even if only to set expectations and discourage misuse.

**Comment by luglio7** [comment]
The v3 documentation should be updated also.
https://v3.vuejs.org/api/special-attributes.html#key

**Comment by NataliaTepluhina** [comment]
@skirtles-code thanks for pointing this out! I've removed the example with `v-for` from docs to prevent confusion
