### ISSUE TITLE
Duplicated word "use" on TypeScript support page

### ISSUE THREAD

**Issue by fnick851** [vuejs/docs-next#403]
On this page: https://v3.vuejs.org/guide/typescript-support.html#typing-refs, there is a small typo.
In "Typing `reactive`" section, it says "...we can use use interfaces.", which I believe should be "...we can use ~~use~~ interfaces."

**Comment by NataliaTepluhina** [comment]
@fnick851 thank you for spotting this! Fixed 👍🏻
