### ISSUE TITLE
Centralize Composition API RFC Docs

### ISSUE THREAD

**Issue by bencodezen** [vuejs/docs-next#408]
Currently we have a second Composition API resource: https://composition-api.vuejs.org/

We should merge these and then redirect from the subdomain to the official guide

**Comment by NataliaTepluhina** [comment]
@bencodezen this is already moved to API reference

**Comment by bencodezen** [comment]
@NataliaTepluhina Thanks for the reminder! 

@sdras wanted to integrate more of the design decisions regarding drawbacks and such into the guide as well since people will probably be asking about things like `ref` vs `reactive`, so I created this to add some of the things back in while also remembering to redirect so people don't feel like there's two official docs on Composition API

**Comment by bencodezen** [comment]
Docs have been centralized.
