### ISSUE TITLE
plugin.md#94 directive demo "bind" should be changed to "mounted"

### ISSUE THREAD

**Issue by johnnywang1994** [vuejs/docs-next#415]
docs-next/src/guide/plugins.md

**Comment by bencodezen** [comment]
Hi @johnnywang1994. Are you referring to the code sample on the page? If so, it'd be great to hear why you think it should be `mounted` instead of `bind`.

**Comment by NataliaTepluhina** [comment]
@johnnywang1994 thank you for spotting this! I've fixed `bind` to `mounted` 👍🏻
