### ISSUE TITLE
Installation section - inconsistent headings

### ISSUE THREAD

**Issue by pearofducks** [vuejs/docs-next#419]
https://v3.vuejs.org/guide/installation.html#from-cdn-or-without-a-bundler

- `vue(.runtime).global(.prod).js` uses code formatting with an h4
- `vue(.runtime).esm-browser(.prod).js` and `vue(.runtime).esm-bundler.js` uses h4
- `vue.cjs(.prod).js` uses code formatting, but under a bullet point

**Comment by NataliaTepluhina** [comment]
Thank you! Fixed 👍🏻
