### ISSUE TITLE
Return values for Application API methods

### ISSUE THREAD

**Issue by skirtles-code** [vuejs/docs-next#423]
The methods in the Application API currently each have a section for `Arguments` but not a section for `Returns`. The returned values are sometimes mentioned in the `Usage` section or in the `Examples` but I think there should be a dedicated section immediately after `Arguments` for `Returns`.

There was something similar in various places in the Vue 2 documentation but most of those methods no longer exist. In the current Vue 3 documentation the only example I could find is for `$watch`.

The returned value is usually the `application`, allowing for chaining, but there are some variations:

* The methods `mixin`, `provide` and `use` just return the current application.
* The methods `component` and `directive` return the current application when two arguments are passed. If only one argument is passed they return the component/directive.
* `mount` returns the root component instance.

I'd be happy to put together a PR for this.

**Comment by NataliaTepluhina** [comment]
@skirtles-code would be happy to see a PR if you're fine with this workload! And thank you for helping us to improve documentation consistently 🙇🏻‍♀️
