### ISSUE TITLE
Directives console error

### ISSUE THREAD

**Issue by skirtles-code** [vuejs/docs-next#424]
If you access the page `/api/directives.html` in a local build of the docs you'll see a console error.

The error relates to this sentence in `directives.md`:

```text
If you need to update the part of `textContent`, you should use `{{ mustache }}` interpolations.
```

The `{{ mustache }}` is being interpreted rather than being treated as literal text. The output looks like this:

![Shaved mustache](https://user-images.githubusercontent.com/65301168/90979012-e07ec880-e549-11ea-8fcd-b63110380841.png)

I'm not really clear whether this is a bug in the underlying engine or just something to be corrected in the documentation. I managed to hack it into submission with:

```html
<template v-pre>`{{ mustache }}`</template>
```

It'd probably be better just to rewrite the whole sentence.

**Comment by NataliaTepluhina** [comment]
Thank you! Fixed 👍🏻
