### ISSUE TITLE
'count.value' should be 'otherCount.value'

### ISSUE THREAD

**Issue by ed1son67** [vuejs/docs-next#425]
In this case，i think 'count.value' should be 'otherCount.value'.

```js
const otherCount = ref(2)

state.count = otherCount
console.log(state.count) // 2
console.log(count.value) // 1
```

locate in https://v3.vuejs.org/guide/reactivity-fundamentals.html#ref-unwrapping

![image](https://user-images.githubusercontent.com/33816744/91002252-b76d3f00-e600-11ea-82cb-c949802f2af5.png)

**Comment by NataliaTepluhina** [comment]
@ed1son67 thank you for opening an issue! No, in this case, `otherCount.value` would be equal to 2. We're referring there a `count.value` from the previous code snippet:

<img width="317" alt="Screenshot 2020-08-24 at 11 50 16" src="https://user-images.githubusercontent.com/18719025/91024036-036bb400-e600-11ea-9f1b-88b0f8e1b5db.png">
