### ISSUE TITLE
Behavior of dropdown menu

### ISSUE THREAD

**Issue by web2033** [vuejs/docs-next#426]
Clicking consequentially on each dropdown menu item does not close the previous item resulting in

![2020-08-24_102404](https://user-images.githubusercontent.com/11320080/91015571-03fe4d80-e5f4-11ea-9e4e-517eee008774.png)

**Comment by NataliaTepluhina** [comment]
@web2033 thank you for reporting this. Unfortunately, this bug is not specific to docs repo, would you mind opening an issue on [Vuepress](https://github.com/vuejs/vuepress) repository instead?

**Comment by billyyyyy3320** [comment]
The issue should be fixed in [v1.5.4](https://github.com/vuejs/vuepress/releases/tag/v1.5.4)
