### ISSUE TITLE
Docs should be clearer about watch option keys not supporting key paths

### ISSUE THREAD

**Issue by DanielAsher** [vuejs/docs-next#437]
Version
3.0.0-rc.9

Reproduction link
https://jsfiddle.net/oekwvhd4/

Steps to reproduce
Migrate a v2 app to v3 with a component that uses a watch option with a key path.

What is expected?
The docs clearly state that watch options no longer support key expressions.

Clear migration guidance should be given about moving watched keypaths to mounted this.$watch(() => this.key.path, () => doSomething())

What is actually happening?
This is a significant (and silent!) breaking change, but the docs still refer to key expressions.

**Comment by NataliaTepluhina** [comment]
@DanielAsher closing this issue as rc.13 supports dot-delimited paths 🎉 

 https://github.com/vuejs/vue-next/commit/1c9a0b3e195d144ac90d22d2cc2cef6a3fd8276d

**Comment by iazz** [comment]
I'm really glad that key paths are now supported in watch options, but that should probably be explicitly mentioned in the docs, as the docs for $watch do mention that they are not, hence the ambiguity.
