### ISSUE TITLE
how to create a components by code? 

### ISSUE THREAD

**Issue by hzmnet** [vuejs/docs-next#444]
how to create a component by code? 
how to new a component instance?

**Comment by hzmnet** [comment]
I want like below codes

`const ComponentClass = Vue.extend(Button)
const instance = new ComponentClass()`

**Comment by NataliaTepluhina** [comment]
https://v3.vuejs.org/guide/component-registration.html#local-registration

Alternatively, you can use [defineComponent](https://v3.vuejs.org/guide/typescript-support.html#defining-vue-components) to enable TypeScript support.

I would also recommend asking questions on Vue Forum/VueLand Discord and then submitting an issue if documentation was not clear.

**Comment by hzmnet** [comment]
sorry i did not using TS. is pure Js.

also the i could new a instance from  defineComponent({})??

how to use defineComponent. in your doc did not told how to new it!
