### ISSUE TITLE
the same code from the docs,why i got the error > "parssing error,Unexpected token"

### ISSUE THREAD

**Issue by ibwei** [vuejs/docs-next#447]
##### As the picture shows:
![image](https://user-images.githubusercontent.com/25237993/91958373-d8890a80-ed39-11ea-87ed-5899123fb67f.png)

#####  The interface book is defined.
![image](https://user-images.githubusercontent.com/25237993/91958604-24d44a80-ed3a-11ea-9976-941b46a847f7.png)

##### The code parts from doc: https://v3.vuejs.org/guide/typescript-support.html#using-with-options-api
![image](https://user-images.githubusercontent.com/25237993/91958897-84325a80-ed3a-11ea-8694-1737166d7e98.png)

##### So,how can i fix the bug?

**Comment by NataliaTepluhina** [comment]
I checked locally and the code works as intended. I would recommend asking for help on [Vue Forum](https://forum.vuejs.org/) or [Vue.js Discord](http://chat.vuejs.org)
