### ISSUE TITLE
Declare global variable for all components

### ISSUE THREAD

**Issue by ammasum** [vuejs/docs-next#466]
In Vuejs 2 we can use global variables like this:
in **main.js**
`import Vue from 'vue'`
`import App from './App.vue'`
`import Axios from 'axios';`
`Vue.prototype.$http = Axios;` 
Then we can use
in **App.vue**
`this.$http.get('somethings')`

But in Vuejs 3 I have tried
`import { createApp } from 'vue'`
`import App from './App.vue'`
`import Axios from 'axios';`
`const app = createApp(App)`
`app.prototype.$http = Axios;`
It's show me can't set $http of undefiend.

How can I set global variables in Vuejs 3?

**Comment by NataliaTepluhina** [comment]
https://v3.vuejs.org/api/application-config.html#globalproperties

Please, don't ask documentation issues as Q&A. I would recommend asking questions on [VueLand Discord channel](http://chat.vuejs.org)
