### ISSUE TITLE
how to new component dynamic by code?

### ISSUE THREAD

**Issue by hzmnet** [vuejs/docs-next#470]
how to Implement the below logic codes?
> 
      var el = document.createElement("vue-component");
      //  var el = new VueComponent()
      var fragment = document.createDocumentFragment();
       ....  here could edit component's Data,Prop values.
       fragment.append(el.$el );

>

**Comment by NataliaTepluhina** [comment]
Sorry but docs repository issues are not the best place to ask for code help. I would recommend asking for help on [Vue Forum](https://forum.vuejs.org/) or [Vue.js Discord](http://chat.vuejs.org)
