### ISSUE TITLE
Add missing CSS modules API

### ISSUE THREAD

**Issue by posva** [vuejs/docs-next#476]
When using the options api, users can directly read from `this.$style` to use CSS modules, when using `setup`, they have to use `useCssModules()` and `useCssVars()`. These two functions seems to be missing from API docs

**Comment by skirtles-code** [comment]
`useCssModule` is now documented: https://v3.vuejs.org/api/global-api.html#usecssmodule

I'm unclear whether `useCssVars` is part of the public API. It seems to be related to the `v-bind`-in-`<style>` feature but from what I can tell from [the RFC](https://github.com/vuejs/rfcs/blob/style-vars-2/active-rfcs/0000-sfc-style-variables.md) it's only intended for internal use by the SFC compiler.

@posva Do you think this can be closed?
