### ISSUE TITLE
Error in sample code in document

### ISSUE THREAD

**Issue by 9kg** [vuejs/docs-next#479]
<https://v3.vuejs.org/guide/mixins.html#custom-option-merge-strategies>

In the **second example**, the order of the parameters in **the 5th line** is wrong

Now it's like this:  app.config.optionMergeStrategies.custom = (`toVal`, `fromVal`) => {

But it should be like this: app.config.optionMergeStrategies.custom = (`fromVal`, `toVal`) => {

The third example is the same

**Comment by NataliaTepluhina** [comment]
@9kg could you please elaborate more why do you think the order is wrong? The `optionMergeStrategies` implementation didn't change much since 2.x (it's an empty object by default now) and on v2 docs it has the same order of parameters: https://vuejs.org/v2/guide/mixins.html#Custom-Option-Merge-Strategies

**Comment by 9kg** [comment]
> @9kg could you please elaborate more why do you think the order is wrong? The `optionMergeStrategies` implementation didn't change much since 2.x (it's an empty object by default now) and on v2 docs it has the same order of parameters: https://vuejs.org/v2/guide/mixins.html#Custom-Option-Merge-Strategies

If you follow the existing order, the actual run output is different with the output in the comment. If the parameter order changes, then everything will be OK.

**Comment by 9kg** [comment]
The comment in the example looks like this
```
// => "goodbye!", undefined
// => "hello", "goodbye!"
```

But the actual output is like this
```
// => undefined, "hello"
// => "goodbye!", "hello"
```

**Comment by NataliaTepluhina** [comment]
@9kg I've created a pen and the output is the same as shown on docs: https://codepen.io/NataliaTepluhina/pen/vYGzeqr

do you have `console.log(fromVal, toVal)` as a 6th row? I have a suspicion the order here might be different

**Comment by 9kg** [comment]
我发现是这样子, 如果你用这种是`https://unpkg.com/vue@next`没问题的
但是如果你是这样子`import { createApp } from "vue";` 再去创建实例就会有我提到的顺序问题

**Comment by 9kg** [comment]
I've seen your example and it's OK
So I ran again in my local, the code is copied, so there is no problem in the `console.log` order, you can rest assured😜

However, after running locally, the log order is still wrong

Then I found that the only difference between us was that the way we created the instance or the package we imported was differen

This is your way
```
// link: https://unpkg.com/vue@next
const app = Vue.createApp({
  custom: 'hello!'
})
```

This is your way
```
import { createApp } from "vue";
const app = createApp(App);
```

and my Vue's version is 3.0.0-rc.10.

**Comment by 9kg** [comment]
I've just seen your Vue version is 3.0.0-rc.13, So this problem should not exist. My version is out of date.
Thank you for your patience!~
