### ISSUE TITLE
'created a video' hyperlink is broken at https://v3.vuejs.org/guide/introduction.html

### ISSUE THREAD

**Issue by pranvatsa** [vuejs/docs-next#499]
At this paragraph  -

>  'If you’d like to learn more about Vue before diving in, we **created a video** walking through the core principles and a sample project.'

Clicking on '**created a video**' hyperlink does not open any video. Redirects to https://v3.vuejs.org/guide/introduction.html# which is the homepage  itself but does not open any link or video.

On older doc-  https://vuejs.org/v2/guide/# docs - 'If you’d like to learn more about Vue before diving in, we created a video walking through the core principles and a sample project.' Click opens up a vimeo player with Gregs talk on intro to vue.

**Comment by pranvatsa** [comment]
Additionally on https://vuejs.org/v2/guide/# docs - 'If you’d like to learn more about Vue before diving in, we created a video walking through the core principles and a sample project.' Click opens up a vimeo player with Gregs talk on intro to vue.

**Comment by NataliaTepluhina** [comment]
@pranvatsa thank you for reporting this! Should be fixed with https://github.com/vuejs/docs-next/commit/f558bf6da533a0d072af222d541d2cd9555ac91d
