### ISSUE TITLE
bugs: cannot found the 'automatically unwrapped' hyperlink

### ISSUE THREAD

**Issue by ajycc20** [vuejs/docs-next#502]
https://v3.vuejs.org/guide/composition-api-setup.html#usage-with-templates

Note that [refs](https://v3.vuejs.org/api/refs-api.html#ref) returned from `setup` are [automatically unwrapped](https://v3.vuejs.org/api/refs-api.html#access-in-templates) when accessed in the template so you shouldn't use `.value` in templates.

**Comment by NataliaTepluhina** [comment]
@ajycc20 thank you for reporting this! Fixed on `master`
