### ISSUE TITLE
Build time intergartion/ Micro frontend using vue 3 ?

### ISSUE THREAD

**Issue by anish2690** [vuejs/docs-next#506]
Can we have more examples of mono-repo config and build time integration using multiple entry points/ micro frontend architecture ?. working with a bigger product with lots of vue components it really hard to work with it due to a large codebase and compile-time issues. we expect some initiative from the vue team to consider the configuration of the large app examples/docs/style guides. And i hope the new vue Devtool has multiple app support.

**Comment by LinusBorg** [comment]
> examples of mono-repo config and build time integration using multiple entry points/ micro frontend architecture 

That's a *very* broad request covering multiple thing that are not nessessarily connected. I'm not sure how you expect us to cover all of the various variations possible.

Also, concerning micro-frontend architecture in particular: that's popular writing and speaking about, but not really common I'm daily projects as of now - at least not common enough for our team members to have worked in various scenarios with such architectures.

We would rather welcome a ln effort of the parts of community that *does* have such experience to start an initiative to come up with guides and resources.

These could be included in the docs' cookbook section, maybe?

> working with a bigger product with lots of vue components it really hard to work with it due to a large codebase and compile-time issues. 

If you have issues, we would like to understand them better. Maybe write up what kind of challenges you are facing as a basis for discission?

> we expect some initiative from the vue team to consider the configuration of the large app examples/docs/style guides. 

Not sure who "we" refers to here, but as explained above, we the Vue team will require on the communitie's input here.

**Comment by NataliaTepluhina** [comment]
Closing this one as stale

**Comment by noook** [comment]
Just found this topic through a lot of googling on how to create micro-frontends architecture.

I guess there is a lot more to that than just Vue, among bundling and serving the different parts of the root app.

I already opened a discussion on Vite's repository [here](https://github.com/vitejs/vite/discussions/3472) to try to collect information and understand how all of that even works, as I clearly don't have the experience as you pointed out in the last message

Here is the idea:
![image](https://user-images.githubusercontent.com/19751938/119006326-915aac80-b990-11eb-9c95-676060d693ac.png)

The "project package" part are actually products and need to be separated from the core repo, and need to be deployed independently, thus our need to split the code at this level.

Can we imagine each app as a package/module we can import in the root app ?
