### ISSUE TITLE
adding examples and modifying parameter descriptions

### ISSUE THREAD

**Issue by zhenzhenChange** [vuejs/docs-next#522]
document: src/api/global-api.md

Modified api:

- defineAsyncComponent

  Advanced Usage, Adding examples to the `onError` hook ([Reference rfc](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0026-async-component-api.md#retry-control)) :
  ```js
  ...
  onError(error, retry, fail, attempts) {
    if (error.message.match(/fetch/) && attempts <= 3) {
      // retry on fetch errors, 3 max attempts
      retry()
    } else {
      // Note that retry/fail are like resolve/reject of a promise:
      // one of them must be called for the error handling to continue.
      fail()
    }
  }
  ...
  ```

- resolveComponent

  Modify parameter descriptions: 
  ```md
  Accepts one argument: `component` --> Accepts one argument: `name`
  ```

**Comment by skirtles-code** [comment]
I believe this has been fixed in #523.
