### ISSUE TITLE
@vue/cli or @vue/cli@next

### ISSUE THREAD

**Issue by painbfb** [vuejs/docs-next#527]
Being a newbie for vue cli, I am confused following the latest vue3 cli doc. 

https://v3.vuejs.org/guide/installation.html#cli

becoz the doc says: `yarn global add @vue/cli@next`, but after I installed, the command line prompts for newer version and gives yet another command `yarn global add @vue/cli `.

so which one is more correct?

**Comment by NataliaTepluhina** [comment]
@painbfb thank you for reporting this! It should be `@vue/cli`, fixed on https://github.com/vuejs/docs-next/commit/3b0492a223ba444da3517794dc72a27a55c2246d
