### ISSUE TITLE
I want to view all API at a glance

### ISSUE THREAD

**Issue by xianghongai** [vuejs/docs-next#528]
In the second edition, all the menus are in the sidebar, and I can make a [second transformation](https://greasyfork.org/zh-CN/scripts/402459-vue-api-dashboard-2-0-0). However, in the third edition, the sidebar is event response, and it is impossible to make a panel like the following:

![Vue-API-Dashboard-Toggle](https://user-images.githubusercontent.com/2075006/93731023-d958e200-fbfd-11ea-80f7-1e20d39d7ad7.png)

![Vue-API-Dashboard](https://user-images.githubusercontent.com/2075006/93731028-de1d9600-fbfd-11ea-9a22-e313306f00af.png)

Hope the official can support this feature,

Thanks.

**Comment by NataliaTepluhina** [comment]
@xianghongai could you please describe, what exact transformation needs to be done?

**Comment by xianghongai** [comment]
@NataliaTepluhina @yyx990803 
I want to have an API Dashboard so that it can display all the APIs in VUE 3.
You can refer to my implementation in VUE 2, as shown in the figure above.

**Comment by xianghongai** [comment]
This is an interactive GIF:

![ui](https://user-images.githubusercontent.com/2075006/93990102-4f577780-fdbd-11ea-8977-d7ae1e2687ee.gif)

**Comment by xianghongai** [comment]
[Vue 2 - API Dashboard: 更方便的查看 Vue API / Better view for Vue API 🌈](https://github.com/xianghongai/Vue-API-Dashboard)

**Comment by NataliaTepluhina** [comment]
@xianghongai from what I understand, the issue here is API now is split onto multiple files rather than one file implementation (like it was on Vue 2). Unfortunately, we don't plan to merge all the API to the same doc as it would be really bloated.

**Comment by yyx990803** [comment]
Hmm, the extension looks more like a cheatsheet. Maybe we can indeed have something like that built-in (by programmatically building on top of sidebar data in a VuePress component).

**Comment by NataliaTepluhina** [comment]
Closing this one as stale
