### ISSUE TITLE
Unable to run examples on website

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/docs-next#532]
![image](https://user-images.githubusercontent.com/33315834/93762648-90774c80-fc42-11ea-9306-84f548b99c32.png)

**Comment by NataliaTepluhina** [comment]
Works for me, probably it's something regarding your browser security settings. Also, you could click `Edit on codepen` to try example

**Comment by igorvolnyi** [comment]
If you have [Smart Referer](https://addons.mozilla.org/en-US/firefox/addon/smart-referer/) addon installed in your FF, you should add one row into it's whitelist:
Source: codepen.io
Destination: cdpn.io

See also #761
