### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by raukaute** [vuejs/docs-next#533]
Hey!

Kind of hard to to find any information on that, so I was wondering if there is any roadmap/schedule for Vue 3 SSR support. The current server-renderer only supports version 2. . I peeked into it, to see if I can somehow tweek it to make it work with Vue 3, but it raises too many issues. I'm using the composition API already, but would really love to migrate one of my SSR apps to Vue 3.

Thanks for clarification!

**Comment by skirtles-code** [comment]
The documentation needs updating but there is already support for SSR in Vue 3.

See [https://github.com/vuejs/vue-next/tree/master/packages/server-renderer](https://github.com/vuejs/vue-next/tree/master/packages/server-renderer)

**Comment by glopezep** [comment]
@skirtles-code Hey, I think He is talking about that "The documentation needs updating"

**Comment by raukaute** [comment]
I wrote up a Vue 3 version of the Vue 2 hackernews clone. It seems to be working quit nicely. 
Also pushed it up to git at <a href="https://github.com/raukaute/vue-hackernews-3.0">https://github.com/raukaute/vue-hackernews-3.0</a>

Maybe it can serve as a reference for others looking for how to migrate existing vue ssr apps.

**Comment by glopezep** [comment]
@raukaute for some reason the styles are not working in the SSR, They are injected but on the client-side

**Comment by raukaute** [comment]
@glopezep 

Thank you for your reply. Can you give a little more detail? I am not 100% sure I know what you mean. 

Cheers

**Comment by glopezep** [comment]
@raukaute sure, the problem is that in SSR the styles can't be rendered using the link tag for example <link ref="example.css" ... />. it should be rendered in inline CSS using the style tag, this is because we need more information about this. because maybe vue has a webpack plugin or loader for that to avoid doing this manually
