### ISSUE TITLE
文案错误？

### ISSUE THREAD

**Issue by XFJGitHub** [vuejs/docs-next#538]
迁移指南 -》 介绍 -》 显着的新功能
是不是要表达显著的新功能？

**Comment by sodatea** [comment]
我们的文档里并没有这句话。我猜你是用了 Google Translate 看到的错误翻译……

另外中文文档可以看 https://v3.cn.vuejs.org/

**Comment by XFJGitHub** [comment]
> 迁移指南 -》 介绍 -》 显着的新功能
> 是不是要表达显著的新功能？
