### ISSUE TITLE
Composition API: Computed value used passed to child component requires reference to .value

### ISSUE THREAD

**Issue by rlagoue** [vuejs/docs-next#547]
Step to reproduce:

1. create a Child component with a prop of type Boolean
2. use the child component in a parent component and pass a computed value of type Boolean

Expected
The computed value is used in the template without referencing the .value field. 

Problem
The computed value's Ref object is passed

The issue does not occurs when the computed value is used in a "v-if" for example

**Comment by NataliaTepluhina** [comment]
@rlagoue thank you for creating the issue! I don't think it belongs to the documentation repository, would you mind creating the same report on https://github.com/vuejs/vue-next issues?
