### ISSUE TITLE
Cosmetic issues on mobile

### ISSUE THREAD

**Issue by Alexn117** [vuejs/docs-next#556]
I’m viewing on iOS Safari, for reference.

1. Scroll down from the very top of the homepage till you get the rubber band effect. There will be hidden object printed on screen.

![87C6D368-7039-43DA-9F12-0155903282D7](https://user-images.githubusercontent.com/29024614/94346023-dee86a80-fff7-11ea-9abc-9fc18e7c7bc7.jpeg)

2. The “K” button in the top right search box is not vertically aligned with the text of its sibling button.

![30A09B19-B50A-4E27-B904-DCA0A0FB3070](https://user-images.githubusercontent.com/29024614/94346053-10f9cc80-fff8-11ea-8526-b64b32f408c6.jpeg)

3. The “Subscribe” button in the footer does not seem to have full mobile styling.

![2554EFA1-AAA1-457B-9370-79A889DD8901](https://user-images.githubusercontent.com/29024614/94346091-6209c080-fff8-11ea-9662-309d41484de1.jpeg)

Just a few cosmetic issues I saw while browsing and thought I’d share them to better the site.

**Comment by anilsahindev** [comment]
@Alexn117 @skirtles-code I created a PR for image 2 https://github.com/vuejs/docs-next/pull/625

**Comment by skirtles-code** [comment]
I believe these have all been fixed now.
