### ISSUE TITLE
Figure caption on `css-vs-js-ease.svg`

### ISSUE THREAD

**Issue by u-sho** [vuejs/docs-next#564]
This is at https://v3.vuejs.org/guide/transitions-overview.html#easing

The `CSS - limited handles` caption is broken.

<img width="1062" src="https://user-images.githubusercontent.com/26079835/94508009-fe77d100-024b-11eb-9503-df6ccb3d0146.png">

**Comment by u-sho** [comment]
I think that these `<tspan>` tags make it wrong.

<img width="1263" src="https://user-images.githubusercontent.com/26079835/94508636-56fb9e00-024d-11eb-8e13-b284f396e93d.png">

**Comment by sdras** [comment]
This seems like it's fixed. I can also give it another cleanup pass in another PR. Thanks!
