### ISSUE TITLE
Problem with no $on support in version 3

### ISSUE THREAD

**Issue by indranilstn** [vuejs/docs-next#569]
I use component extensions extensively to keep things modular. A base component would $emit an event and it would be available to higher level components through $on for additional tasks to be done. That way the same event is used by higher level components that extends the base component and any parent component. With no $on support in version 3, could you suggest a work around for this scenario?

**Comment by NataliaTepluhina** [comment]
@indranilstn we did recommend using an external implementation of event emitter: https://v3.vuejs.org/guide/migration/events-api.html#migration-strategy

**Comment by indranilstn** [comment]
External event emitter would be a good replacement for an event bus. Let me give an example of the scenario where it would look forced.

var CompA = { ... }

// extend CompA without having to call `Vue.extend` on either
var CompB = {
  extends: CompA,
  ...
}

CompC is a parent component that has CompB as a child.

In my code, when CompA emits a 'closed' event, then both CompC and CompB would process this event and do some work. It is hard to migrate this code to version 3 without emitting the same event 'closed' twice - once using $emit so that CompC can process it as the parent component and then again fire the same event through the external emitter so that CompB can process it.

Is there any better approach than using two events, one for parent and another for the component extension hierarchy?

**Comment by NataliaTepluhina** [comment]
@indranilstn unfortunately, I don't see an alternative in this case. I would also recommend asking on [Vue Forum](https://forum.vuejs.org/) or [VueLand Discord channel](http://chat.vuejs.org) to get more support.
