### ISSUE TITLE
$nextTick

### ISSUE THREAD

**Issue by shaan1974** [vuejs/docs-next#574]
Hello,

When i use "this.$nextTick" inside the function, "this" return the current instance with Vue 2
[Vuejs 2 fiddle](https://jsfiddle.net/shaan1974/qf4umgh2/)

But with Vue 3 it return the window object.
[Vuejs 3 fiddle](https://jsfiddle.net/shaan1974/rokqebcL/)

( Just take a look into the console )

Is it normal ?

Best regards
Shaan

**Comment by skirtles-code** [comment]
I believe you're correct. As far as I'm aware this is not an intentional change and it is a bug in Vue 3.

Could you file an issue in the [vue-next](https://github.com/vuejs/vue-next/issues) repo?

**Comment by shaan1974** [comment]
Done thanks

Shaan
