### ISSUE TITLE
incomplete documentation for createRenderer

### ISSUE THREAD

**Issue by telic** [vuejs/docs-next#577]
The documentation of createRenderer does not include a summary of its purpose and does not describe its parameter object. What is `patchProp`? What are `…nodeOpts`?

Furthermore, the generic type parameters are confusingly described as "arguments" in the same way that formal parameters are described for other functions on this page.

**Comment by NataliaTepluhina** [comment]
A duplicate of https://github.com/vuejs/docs-next/issues/116
