### ISSUE TITLE
Catching error: Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/docs-next#611]
![image](https://user-images.githubusercontent.com/33315834/95437595-c1b48400-0987-11eb-8a04-5b600ff5e078.png)

I cannot open folded sidebars such as 
![image](https://user-images.githubusercontent.com/33315834/95437781-fde7e480-0987-11eb-823d-b25347e69a30.png)

Addtional Info:

Chrome version: 85.0.4183.121

**Comment by phanan** [comment]
Thanks for reporting the issue, but 1. I can't reproduce it and 2. It would still be trivia enough to ignore.

![image](https://user-images.githubusercontent.com/8056274/95459532-164e0400-0974-11eb-9c56-b7300a2aee5a.png)
