### ISSUE TITLE
cannot see the lifecycle-diagram  image clear

### ISSUE THREAD

**Issue by calali** [vuejs/docs-next#618]
here's the link:https://v3.vuejs.org/guide/instance.html#lifecycle-diagram

**Comment by skirtles-code** [comment]
In what sense is it not clear?

**Comment by calali** [comment]
The picture is blurred
![image](https://user-images.githubusercontent.com/15995588/95701904-6206f300-0c7d-11eb-9390-8445b10ad7c2.png)

**Comment by skirtles-code** [comment]
Odd.

I'm assuming you're using a device with a high pixel ratio but, even so, that's very distorted

**Comment by sdras** [comment]
Can you please let us know your OS and browser?

**Comment by calali** [comment]
I'm sorry for late reply.My mac's os is macOS Mojave and it's version is 10.14.6 (18G6032).
And the browser is Google Chrome, it's version is 87.0.4280.67（official version） (x86_64).

**Comment by 7NZ** [comment]
![snipaste_20201123_140618](https://user-images.githubusercontent.com/22293413/99933135-1b84d800-2d95-11eb-8e9f-c92f7eb59668.png)
same.
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
os	Windows 10 pro
osVersion	20H2

**Comment by skirtles-code** [comment]
This should be fixed by #767.
