### ISSUE TITLE
TypeScript, template refs and computed property

### ISSUE THREAD

**Issue by kreha1** [vuejs/docs-next#624]
https://v3.vuejs.org/guide/composition-api-template-refs.html#template-refs

The following example doesn't explain how to correctly use ref inside computed function.
Inside of `setup()`:
```
const element = ref(null); // type is Ref<null>
const width = computed(() => element.value.clientWidth) // Object is possibly 'null'. 
// or
const width = computed(() => element.value?.clientWidth) // Property 'clientWidth' does not exist on type 'never'.

// asserting type during assignment
const element = ref<HTMLElement>(null); // Argument of type 'null' is not assignable to parameter of type 'HTMLElement'.
```
The one way TypeScript is happy with:
```
const element = ref(null as unknown as HTMLElement);
const width = computed(() => element.value.clientWidth);
```
So I end up declaring it: `const width = computed(() => root.value.clientWidth).value;`
but when I `return { width }` the template isn't being rendered.

**Comment by LinusBorg** [comment]
You can use the generic:
```

const element = ref<HTMLElement | undefined>()
```

Allowing `undefined` as a possible value is correct as the ref can be empty at any point thoughout its lifetime.

In your computed (or anywhere else that you read from this ref) you should verify that the value actually is an element (i.e. with optional chaining) before reading a property:

```typescript
const width = computed(() => element.value?.clientWidth);
```

**Comment by LinusBorg** [comment]
I'll close this as Typescript documentation as a whole is still an open issue
