### ISSUE TITLE
Wrong URL on `src/style-guide/README.md`?

### ISSUE THREAD

**Issue by Tintef** [vuejs/docs-next#627]
In [this file](https://github.com/vuejs/docs-next/blob/master/src/style-guide/README.md) on the "Prop definitions" rule, the link to the detailed explanation is pointing to the v2 docs, is this intended? (line ~85)

```
::: details Detailed Explanation
Detailed [prop definitions](https://vuejs.org/v2/guide/components.html#Prop-Validation) have two advantages:
```

**Comment by phanan** [comment]
It should indeed point to the [new doc](https://v3.vuejs.org/guide/component-props.html#prop-validation). Do you want to create a PR?

**Comment by Tintef** [comment]
@phanan Sure, I'll create a PR 😄 

I also noticed a couple more occurrences of this on the same file:

```
### Non-flux state management <sup data-p="d">use with caution</sup>

**[Vuex](https://github.com/vuejs/vuex) should be preferred for global state management, instead of `this.$root` or a global event bus.**

Managing state on `this.$root` and/or using a [global event bus](https://vuejs.org/v2/guide/migration.html#dispatch-and-broadcast-replaced) can be convenient for very simple cases, but it is not appropriate for most applications.

Vuex is the [official flux-like implementation](https://vuejs.org/v2/guide/state-management.html#Official-Flux-Like-Implementation) for Vue, and offers not only a central place to manage state, but also tools for organizing, tracking, and debugging state changes. It integrates well in the Vue ecosystem (including full [Vue DevTools](https://vuejs.org/v2/guide/installation.html#Vue-Devtools) support).
```

I'm not sure where the `[global event bus]` one should point to, but I think the other ones should be:
- [official flux-like implementation](https://v3.vuejs.org/guide/state-management.html#official-flux-like-implementation)
- [Vue DevTools](https://v3.vuejs.org/guide/installation.html#vue-devtools)

What do you think?

**Comment by phanan** [comment]
Hmm. Since Vue 3 no longer implements an event emitter interface, using a Vue instance as a global event bus wouldn't work anyway. Since "event bus" is a general programming concept/pattern, I think we can remove the link altogether. 

For the latter, the first link to "Official flux-like implementation" should indeed work.
