### ISSUE TITLE
watch: watching multiple sources TypeScript

### ISSUE THREAD

**Issue by JensD98** [vuejs/docs-next#630]
Hi, I recently ran into a problem while using the new reactivity API `watch` function in TypeScript. Take a look at the following example, the types for `a` and `b` are merged even though they should be seperated:

```ts
let a: string | undefined
let b: boolean = false

watch([a, b], ([a, b], [prevA, prevA]) => {
  // a and b will be of type string | undefined | boolean
  // a should be string | undefined
  // b should be boolean
})
```

I realized that you can add `as const` to the source array to get correct type inference:

```ts
let a: string | undefined
let b: boolean = false

watch([a, b] as const, ([a, b], [prevA, prevA]) => {
  // types are now correct
  // a is of type string | undefined
  // b is of type boolean
})
```

It would be nice if the usage can be added to the docs (if it's an appropriate solution). Here is a link to the example in [TS playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBA6ghsAxgCwgJwMoHsCubEQA8AKgHxQC8UxUAPlABQMCUl5xzAUJ6JFALJww2PAQDOJclQDenKFADaAaSgBLAHZQA1hBBYAZtQC6ALmrKjUCAA9gEdQBMxsBCnQj8RDfvRQAauQA-P5QZuoQAG7onAC+3Po46ojAqliaAO6uyCRWtvZOUGgQcA5pADYgLkiomLiehIla6ljp6qQKRqQMclBideJmxAA0PYhwZWUARnCIWmYMEeM4EGJmgsL9K5JDUFhlDn5LK2tCHuKSrBTkEViqDpyssvIA9M9QAHSfsdxlEMBQcDMYmAaA0AHM6FBEg4IPoNBB7r9-pMzJMsHtipoqPpxmIINxXrBVMBkFBEGlgQCxHi0Ck0pxCchgMAwKtXukOe9eCtEKCwMAynB1GD3lg0GDnqVEGJnsghQ40VgtM8ir84HiALTNOwy7liXmqfkagDMGoALO8mQBbMoAYnJ6mBGvVNLpjs4mWqDAULDYAJ2k0s6rJFOAO29cADRh2CjARQiAEEdnHIgAhIyXchPEOO-5wABMQJB4Mh0Nh8IclABo1DUEmhbr6LVWLr3HkDspKcTDeBoOFpcc5fClaoXYTNdzUC7qYbiubVensS4DLeMGJyFw-w7eep6DdHqy3t9V39dejjAUkbPMbHyfj6czUGz24BPeL-foZbhw6rcAnlPrVEm0xKtJjbHNO3jBM3z7CFP0Hb8EQXKD-3+adZ2AoVkLTJcgA). Cheers!

**Comment by monadev13** [comment]
wwwww
reeeee
hhhhhh

**Comment by monadev13** [comment]
bbbbbbbbbbbbbbbbbb
