### ISSUE TITLE
Wrong value given to the custom directive in migration guide

### ISSUE THREAD

**Issue by boussadjra** [vuejs/docs-next#632]
In the example given in the migration guide concerning the custom directive hooks with [Vue 3 syntax](https://v3.vuejs.org/guide/migration/custom-directives.html#_3-x-syntax), we see the following example :

        <p v-highlight="yellow">Highlight this text bright yellow</p>

which cannot work because it will raise the following error : 

>[Vue warn]: Property "yellow" was accessed during render but is not defined on instance.

the correct value should be done as string or the `yellow` value should be defined as property :

      <p v-highlight="'yellow'">Highlight this text bright yellow</p>

[Reproduction Link](https://codesandbox.io/s/using-vuex-4-modules-in-vue-3-with-typescript-forked-pzrte?file=/src/App.vue)

**Comment by skirtles-code** [comment]
Fixed in #634.
