### ISSUE TITLE
After clicking the navbar Docs, when the mouse leave, dropdown does not disappear

### ISSUE THREAD

**Issue by tangyouge** [vuejs/docs-next#635]
Like the title, after clicking Docs,Ecosystem and Support Vue, a dropdown appears, but when you click again, the dropdown does not disappear. It should be that the hover event is normal, and there is a problem with the click.

**Comment by NataliaTepluhina** [comment]
@tangyouge thank you for reporting this! However, this is rather a platform issue (Vuepress in this case) so I don't think this issue is relevant for docs project
