### ISSUE TITLE
Vue 3 security page

### ISSUE THREAD

**Issue by ajbfenwick** [vuejs/docs-next#643]
Vue 2 docs have a very handy '[Security](https://vuejs.org/v2/guide/security.html)' page that walks users through what Vue does to mitigate concerns, what the potential dangers are etc.

As far as I can see the Vue 3 docs have no such guide yet? Are there plans to write one? Can I for now assume the Vue 2 security page applies to Vue 3?

I'm very much new to Vue and one of the things that has impressed me so far is the detailed documentation. As such it was a bit of a treat to come across the security page in the Vue 2 docs and I think it would be just as welcome in the Vue 3 docs.

I apologise if this issue seems more of a suggestion but considering the ever-increasing importance of cyber security I thought it warranted raising as an issue.

**Comment by NataliaTepluhina** [comment]
@ajbfenwick  thank you for creating an issue! I believe it's a good idea to add a Security page to Vue 3 documentation too.
