### ISSUE TITLE
Installation | npm install vue@next

### ISSUE THREAD

**Issue by abelardolg** [vuejs/docs-next#644]
Hi there,
When I typed this command, the output was:
npm WARN saveError ENOENT: no such file or directory, open '/home/curso/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/curso/package.json'
npm WARN curso No description
npm WARN curso No repository field.
npm WARN curso No README data
npm WARN curso No license field.

Inside the doc, no package.json was mentioned.

Is mandatory to have a package.json in order to have installed vuejs?

I suggest a better explanation about how to install vuejs and the prerrequisites.

Best regards.

**Comment by phanan** [comment]
This is not a problem with vue, but with how to use npm with your project. Installing vue with npm is no different than any other package. I'd suggest reading an entry-level guide to npm, e.g., https://nodesource.com/blog/an-absolute-beginners-guide-to-using-npm/.
