### ISSUE TITLE
Global API sidebar showing unnecessary sub headers

### ISSUE THREAD

**Issue by yyx990803** [vuejs/docs-next#645]
https://v3.vuejs.org/api/global-api.html

It's showing a lot of `Arguments` and `Typing` sub headers which makes it a bit difficult to scan. We should probably convert the `Arguments` and `Typing` from headers to a list format similar to [Instance methods](https://v3.vuejs.org/api/instance-methods.html#watch).

**Comment by NataliaTepluhina** [comment]
Fixed via https://github.com/vuejs/docs-next/commit/6ba05d1e2cdd548038ad247f63288144b622d61f
