### ISSUE TITLE
TodoMVC "hashtag navigation will not work" is the code's bug, nothing about CodePen's limitation

### ISSUE THREAD

**Issue by elechen** [vuejs/docs-next#659]
> Additionally, due to limitations on CodePen, hashtag navigation will not work.

[this is the page](https://v3.vuejs.org/examples/todomvc.html)

actually is not about CodePen limitation. the **app** is not the root vue component instance, but the result **app.mount(".todoapp")** returns should be. [api about mount](https://v3.vuejs.org/api/application-api.html#mount)

here is the code to fix it

```js
const vm = app.mount(".todoapp");
function onHashChange() {
  var visibility = window.location.hash.replace(/#\/?/, "");
  if (filters[visibility]) {
    vm.visibility = visibility;
  } else {
    window.location.hash = "";
    vm.visibility = "all";
  }
}
```

**Comment by NataliaTepluhina** [comment]
@elechen thank you! Example fixed 👍🏻

**Comment by takatama** [comment]
The bug in CodePen has not been fixed yet.

The buggy CodePen:
https://codepen.io/team/Vue/pen/Yzqyozj

I forked and fixed the bug:
https://codepen.io/takatama/pen/ExNZwQO

**Comment by skirtles-code** [comment]
Agreed. It needs to update `vm.visibility`, not `app.visibility`, where `vm` is the root instance returned by `mount`.

**Comment by NataliaTepluhina** [comment]
@takatama @skirtles-code even with the fixed code, CodePen still limits us with the hashtag navigation. It shows up on @takatama sandbox as well, there is no URL hash changes on routing (visible on the full page version). Maybe we just need to move this example over to CodeSandbox where navigation seems to work like on 'real' browser.

**Comment by skirtles-code** [comment]
@NataliaTepluhina It looks like you've applied the changes to the live version and it seems to be working correctly now. The buttons at the bottom of the example are updating the hash and the filtering is changing. The Back/Forward buttons in the browser also seem to work fine. It isn't possible to see the URL directly in the address bar but I don't think that's really a problem.

Or is there another problem I'm not seeing?

**Comment by NataliaTepluhina** [comment]
@skirtles-code hmmm I was considering a non-changing hash in the URL an issue but happy to close this one if you find the fix to be sufficient 😅
