### ISSUE TITLE
the watchEffect options default flush is pre??

### ISSUE THREAD

**Issue by wocaatm** [vuejs/docs-next#676]
![image](https://user-images.githubusercontent.com/11764069/98348884-401e4780-2054-11eb-9dbe-e1707feeea02.png)

The Doc say that the watcheffect options about flush is pre ? But when I read the source code , I find that the default options about flush is undefined. so the effect cb will call after the component updated

![image](https://user-images.githubusercontent.com/11764069/98349242-b58a1800-2054-11eb-9094-8b66ca646266.png)

see the console in browser

![image](https://user-images.githubusercontent.com/11764069/98349851-77412880-2055-11eb-891d-12ac44455e31.png)

**Comment by LinusBorg** [comment]
You seem to be looking at an out-of date version of the source, what version did you check?

https://github.com/vuejs/vue-next/blob/43579a8de358846de96d0d789eebbebf95b2f391/packages/runtime-core/src/apiWatch.ts#L266-L269

**Comment by wocaatm** [comment]
> You seem to be looking at an out-of date version of the source, what version did you check?
> 
> https://github.com/vuejs/vue-next/blob/43579a8de358846de96d0d789eebbebf95b2f391/packages/runtime-core/src/apiWatch.ts#L266-L269

ok，the souce code is out-of date, thx
