### ISSUE TITLE
Move the migration and contribution guidelines in separate sections

### ISSUE THREAD

**Issue by gtsiolis** [vuejs/docs-next#693]
### Problem

Currently, the _Migration Guide_ and _Contribute to the Docs_ section are nested in the sidebar under the first docs section (_Guide_). Here're are some minor issues caused by this nesting:

1. **Navigation:** When you click the Migration Guide link from the Docs dropdown menu, the sidebar is not scrolling to the relevant section which could cause confusion. For example, if you're on the top of the [Template refs](https://v3.vuejs.org/guide/component-template-refs.html) section and then click on the _Migration Guide_ from the _Docs_ dropdown, it's not clear there's a list of relevant sub-sections you can navigate to.
1. **Copy**: The Docs dropdown is repeatedly using the _Guide_ keyword in the dropdown options.
1. **Discoverability**: It's hard to locate contribution guidelines.

### Proposal

WDYT of the following?

1. Move the migration and contribution guidelines in a separate top-level sections with their own sidebar.
1. Update the _Docs_ dropdown with something like the following (see screenshots).

| BEFORE | AFTER |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/99154684-56627e00-26ba-11eb-8f10-3edfea3c9f60.png) | ![image](https://user-images.githubusercontent.com/120486/99154686-5a8e9b80-26ba-11eb-8c3f-5d88f5d6e4f2.png) |

**Comment by skirtles-code** [comment]
I have also found it difficult to navigate within the Migration Guide because of its inclusion in the main Guide sidebar. I would be in favour of using a separate sidebar for the Migration Guide.

From a naming perspective, I wonder whether *'Migration from Vue 2'* in the menu would be more helpful. Someone with an existing application written in jQuery or Angular might be expecting the 'Migration Guide' to be something very different.

**Comment by gtsiolis** [comment]
Hi @skirtles-code!

> From a naming perspective, I wonder whether ...

Agree, this sounds more accurate for sure. Let's loop in @NataliaTepluhina and @bencodezen in case they have more insights on whether this sounds good or a viable solution.

**Comment by NataliaTepluhina** [comment]
@skirtles-code @gtsiolis I agree with you both and I actually wanted to do this earlier but we had a link to the Migration guide promoted on Twitter/Evan's conference talks. I believe now we can safely move it to the separate section

**Comment by skirtles-code** [comment]
I wasn't expecting the URLs to change. Can it be moved to a separate sidebar without changing the URLs?

**Comment by NataliaTepluhina** [comment]
@skirtles-code I've checked and it's actually possible, we just need to define a `guide/migration` in the sidebar settings before `guide`
