### ISSUE TITLE
Uncaught TypeError: Cannot read property 'currentRoute' of undefined

### ISSUE THREAD

**Issue by shuyuhan01** [vuejs/docs-next#695]
vue3 build 之后上线 提示找不到路由
const ctxt = getCurrentInstance()；
ctxt["ctx"].$router.currentRoute.value.name

ctxt["ctx"] 里面找不到&router
 本地开发有这个属性
有遇到的大佬么？

**Comment by NataliaTepluhina** [comment]
I believe this issue should be opened on VueRouter repo as we don't cover router in the core documentation.

**Comment by shuyuhan01** [comment]
https://segmentfault.com/q/1010000038182104


> I believe this issue should be opened on VueRouter repo as we don't cover router in the core documentation.



> 我相信应该在VueRouter存储库上打开此问题，因为我们没有在核心文档中介绍路由器。

https://segmentfault.com/q/1010000038182104
 Please open this link, there are detailed questions, thank you

**Comment by caitoucom** [comment]
遇到了相同的问题，不知道您有没有解决呢

**Comment by shuyuhan01** [comment]
> 遇到了相同的问题，不知道您有没有解决呢

您好！有解决。我是在router 的文件里面的index.ts
import { createRouter, createWebHashHistory, RouteRecordRaw } from "vue-router"
const rouTer = createWebHashHistory(process.env.BASE_URL).state.current
store.dispatch('setrouTer',rouTer)
通过这样的形式 刷新浏览器就可以找到当前路由所要的信息
