### ISSUE TITLE
Clarify/list out what kind of properties could be accessible in template syntax

### ISSUE THREAD

**Issue by maxloh** [vuejs/docs-next#710]
[Vue's documentations](https://v3.vuejs.org/guide/template-syntax.html#text) are not quite clear about what kind of properties could be accessible in template syntax, or in `this`.

It would be easier to understand if we list out those properties available in template syntax, and provide a link to their respective documentations, in a format like the following.

- [Data properties](https://v3.vuejs.org/api/options-data.html#data-2)
- [Computed properties](https://v3.vuejs.org/api/options-data.html#computed)
- [Component props](https://v3.vuejs.org/guide/component-props.html)
- [Returned variables from setup function](https://v3.vuejs.org/guide/composition-api-setup.html#accessing-component-properties)
- Any more?

**Comment by skirtles-code** [comment]
There is some discussion of this on the previous page of the documentation:

https://v3.vuejs.org/guide/instance.html#component-instance-properties

All of the properties of `this` (also referred to as `vm`) are available in the template. The section I referenced lists the component options that are typically used to create those properties.

There are other ways that properties can be created. e.g. They might be added directly to the component instance inside a lifecycle hook. Or they might come from `globalProperties`.

Vue also provides some properties by default, prefixed with `$`. Just like all the other properties of `this` they can be accessed in the template.

**Comment by maxloh** [comment]
> There is some discussion of this on the previous page of the documentation:
> 
> https://v3.vuejs.org/guide/instance.html#component-instance-properties
> 
> All of the properties of `this` (also referred to as `vm`) are available in the template. The section I referenced lists the component options that are typically used to create those properties.
> 
> There are other ways that properties can be created. e.g. They might be added directly to the component instance inside a lifecycle hook. Or they might come from `globalProperties`.
> 
> Vue also provides some properties by default, prefixed with `$`. Just like all the other properties of `this` they can be accessed in the template.

It would be better if you can provide a link to the `component-instance-properties` page, so as to refresh reader's memory.
