### ISSUE TITLE
The part about "boolean attributes" can be more clear.

### ISSUE THREAD

**Issue by oebrab** [vuejs/docs-next#711]
The doc about [boolean attributes](https://v3.vuejs.org/guide/template-syntax.html#attributes) says:

> If `isButtonDisabled` has the value of `null` or `undefined`, the disabled attribute will not even be included in the rendered `<button>` element.

To be more clear, not only `null` or `undefined`, all falsy values mean not disabled, while all truthy values mean disabled.

**Comment by skirtles-code** [comment]
I think there may be even more nuance lurking beneath the surface here.

From what I can tell:

* Normal (non-boolean) attributes will be omitted if their value is `undefined` or `null`. All other values are converted to strings.
* For boolean attributes the values `undefined`, `null`, `false`, `0` and `NaN` will lead to the attribute being omitted. All other values, including an empty string, will result in the attribute being included, though without a value.

**Comment by oebrab** [comment]
Thanks! Learned a lot.

**Comment by skirtles-code** [comment]
I'm going to have a go at updating this unless I hear otherwise.
