### ISSUE TITLE
ESLint: The template root disallows 'v-for' directives：看3.0的介绍说是支持多个root，那么请问支持在root component上用v-for吗

### ISSUE THREAD

**Issue by leeboo** [vuejs/docs-next#720]
![image](https://user-images.githubusercontent.com/1256745/100618005-35568a00-3356-11eb-846a-0bfe2c89a371.png)

**Comment by NataliaTepluhina** [comment]
Thank you for opening the issue! However, I believe, it doesn't belong to the docs repo and should be open in [eslint-plugin-vue repository](https://github.com/vuejs/eslint-plugin-vue/)

Also, we ask people to open issues and PRs in English, as the docs team is not entirely Chinese-speaking.

**Comment by leeboo** [comment]
got it, thanks
