### ISSUE TITLE
break change of watch not in migration doc yet

### ISSUE THREAD

**Issue by LongTengDao** [vuejs/docs-next#722]
the first function argument `expOrFn` of `this.$watch` (and Vue.watch) will not receive the first argument `vm` which equals to `this` any more.

btw: the third argument `onInvalidate` of `cb` is not introduced yet.

**Comment by skirtles-code** [comment]
I tried this myself and I see the same change:

* Vue 2: https://jsfiddle.net/skirtle/5mhLtuqx/
* Vue 3: https://jsfiddle.net/skirtle/fo1bh34x/

@LongTengDao Do you have any confirmation that this is an intentional change and not just a bug?

**Comment by LongTengDao** [comment]
> Do you have any confirmation that this is an intentional change and not just a bug?

Oh, I don't, it could be a bug. Let me ask. https://github.com/vuejs/vue-next/issues/2731

**Comment by NataliaTepluhina** [comment]
Closing this issue as it's confirmed to be a bug on core repo. Please feel free to reopen if anything is not covered in docs after the fix for the mentioned bug is merged!
