### ISSUE TITLE
sample code with new composation api

### ISSUE THREAD

**Issue by softboy99** [vuejs/docs-next#725]
Hi,
this doc site is for vue3.0, please update your sample code with new composation api or supply 2 version on the page. Now, in the site, so many sample code still use "this", "methods". of course, we know vue3.0 still support old options api. But for new comer who want to use and learn vue3.0 only, it will be very confusable. some part are composation api code in your doc, some part are old code. It will stop them from vue ecology. Thanks a lot for your great help.

**Comment by NataliaTepluhina** [comment]
Hi @softboy99! Options API is not 'old' or 'Vue 2' API, it still remains as valid as the Composition API and we decided to leave it as the main learning path for people just picking up Vue. Composition API is designed to solve the problem of code abstraction and reusability mostly, so we start with it a bit later.

Still, nothing is set in stone and if we see that people naturally start picking up Composition API more often, we will change the guide accordingly (similar to how React docs were sticking for a long time with classes and now being rewritten to hooks)

Thank you again for your opinion!

**Comment by softboy99** [comment]
Hi，
Thanks, ok, if so, could you please make notes on the doc that this is code options api or composition api?some code are combined together these two.
