### ISSUE TITLE
Bug in vue 3 dynamic directive arguments doc demo?

### ISSUE THREAD

**Issue by robinzimmermann** [vuejs/docs-next#728]
The page is https://v3.vuejs.org/guide/custom-directive.html#dynamic-directive-arguments

The demo is the second codepen demo in the dynamic directive arguments section. Screenshot:

![image](https://user-images.githubusercontent.com/725660/101066012-b8d8cc80-354a-11eb-8693-c3692a6efde7.png)

When you change the range field, the text moves as expected. However the `200px` in the text doesn't update.

The code for that line is:

```html
<p v-pin:[direction]="pinPadding">Stick me {{ pinPadding + 'px' }} from the {{ direction }} of the page</p>
```

Since it's referring to `{{ pinPadding + 'px' }}`, I would expect it to update whenever `pinPadding` updates, which occurs when you change the range field.

Here is a screenshot of the text clearly at less than 200px, proving that `pinPadding` changed, but the text is unchanged:

![image](https://user-images.githubusercontent.com/725660/101066441-44525d80-354b-11eb-8429-2c1e67cb1dc5.png)

**Comment by NataliaTepluhina** [comment]
@robinzimmermann thank you for catching this! I've updated the codepen 👍🏻
