### ISSUE TITLE
Lifecycle Diagram image are really blurry!

### ISSUE THREAD

**Issue by EdisonVan** [vuejs/docs-next#751]
doc url:  https://v3.vuejs.org/guide/instance.html#lifecycle-hooks
The image of lifecycle diagram are breezing!

**Comment by NataliaTepluhina** [comment]
@EdisonVan thank you for reporting the issue! Could you please share your screen resolution? The diagram looks good on both MacBook screen and 2560x1440px PC monitor

**Comment by EdisonVan** [comment]
1920*1080 , thanks

**Comment by d4g0** [comment]
I can add it seem blurry at 1600x900 too

**Comment by sdras** [comment]
This should be an SVG anyways- I can take this one @tertia
