### ISSUE TITLE
Codepen changed license for SpliText plugin

### ISSUE THREAD

**Issue by igorvolnyi** [vuejs/docs-next#761]
### Version
3.0.4

### Reproduction link
[https://v3.vuejs.org/guide/reactivity.html](https://v3.vuejs.org/guide/reactivity.html)

### Steps to reproduce
Go to https://v3.vuejs.org/guide/reactivity.html#how-vue-tracks-these-changes

### What is expected?
Code demonstration from Codepen

### What is actually happening?
Black frame with a warning saying "Oops! Trial version of SplitText deployed"

---
See screenshot

![VueJS documentation glitch - Codepen membership required 2020-12-23_16-18](https://user-images.githubusercontent.com/11294353/102991719-99c2ce80-453b-11eb-8172-d499699580e0.png)

**Comment by skirtles-code** [comment]
Similar to #532.

@igorvolnyi Do you have any browser plugins or unusual security settings that might explain why you're seeing this message? Do you see the same thing in other browsers or in Incognito/Private mode?

**Comment by igorvolnyi** [comment]
The culprit is the [Smart Referer](https://addons.mozilla.org/en-US/firefox/addon/smart-referer/) FF addon. I can't figure out what to write into my whitelist, so for now I'm resorting to disable the addon in order to view the  content.
So maybe instead of just closing the issue could somebody find the right whitelist combination in order to play the embedded content again without disabling the addon?

**Comment by igorvolnyi** [comment]
I found the solution. In whitelist settings of the addon one should add the following:
Source: codepen.io
Destination: cdpn.io

**Comment by skirtles-code** [comment]
I can now reproduce this in Chrome. It works fine the first time but I see the error when I click on the green Replay button at the end. I don't see any problems with Firefox.

The button just calls `location.reload()`. It seems that reloading changes the `referer` in Chrome but I haven't debugged this in detail.
