### ISSUE TITLE
The image missing

### ISSUE THREAD

**Issue by jiangjunfeng98** [vuejs/docs-next#762]
images `Vue Option API: Code grouped by option type`  missing

[composition-api-introduction](https://github.com/vuejs/docs-next/blob/master/src/guide/composition-api-introduction.md)  60 line

**Comment by skirtles-code** [comment]
The image seems to be there for me. Could you try again, maybe it was just a temporary problem?

**Comment by skirtles-code** [comment]
Closing this for now. We can reopen it if anyone can provide further information about the problem.
