### ISSUE TITLE
Self-referencing components are an undocumented breaking change

### ISSUE THREAD

**Issue by palant** [vuejs/docs-next#765]
The template compiler behavior changed for the following case:

    <template>
      <custom-component />
    </template>

With Vue 2 this would always resolve `custom-component` via component registration. With Vue 3, if this file is named `CustomComponent.vue` (camel-cased version of the tag name) this is automatically considered a self-reference, regardless of the component registration. While this behavior is intentional judging from the source code, it actually caused an infinite recursion in my code because of an unintended self-reference. So it needs to be documented in “Migration from Vue 2” at the very least.

For reference, the relevant commit: https://github.com/vuejs/vue-next/commit/67d1aac6ae683a3a7291dff15071d1eeacb7d22a

**Comment by skirtles-code** [comment]
There does seem to be an open discussion about how exactly this should work: https://github.com/vuejs/vue-next/issues/2827#issuecomment-748457821. See also https://github.com/vuejs/vue-next/issues/2821.

**Comment by skirtles-code** [comment]
This has been changed in 3.0.8. It should now be consistent with Vue 2. The name of the file is now only taken into account if all else fails.
