### ISSUE TITLE
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.

### ISSUE THREAD

**Issue by tjl-cmd** [vuejs/docs-next#806]
vue3.0打包之后整个项目都卡顿，切换路由都卡

**Comment by tjl-cmd** [comment]
整个项目都没有用到'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.中任何一个

**Comment by NataliaTepluhina** [comment]
If Google Translate is correct, I don't think this issue is relevant for the documentation repository. Please open an issue on [vue-next](https://github.com/vuejs/vue-next)
