### ISSUE TITLE
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.  页面打包后整个路由都卡顿，开发模式下正常运行，不卡顿，无论是用router-link或者push都会卡顿

### ISSUE THREAD

**Issue by tjl-cmd** [vuejs/docs-next#809]
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.  页面打包后整个路由都卡顿，开发模式下正常运行，不卡顿，无论是用router-link或者push都会卡顿

运行环境

{
  "name": "ddd",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^3.0.5",
    "vue-class-component": "^8.0.0-0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0",
    "axios": "^0.21.0",
    "element-plus": "^1.0.1-beta.5",
    "vuex-persistedstate": "^4.0.0-beta.1",
    "vuedraggable": "^4.0.1"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^2.33.0",
    "@typescript-eslint/parser": "^2.33.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-typescript": "^5.0.2",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0-0",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "typescript": "~3.9.3"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended",
      "@vue/typescript/recommended"
    ],
    "parserOptions": {
      "ecmaVersion": 2020
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
问题截图，整个页面就一个这样的问题
![image](https://user-images.githubusercontent.com/48304854/104541585-d70f0d80-565c-11eb-95df-fbf9b8739fb8.png)

**Comment by skirtles-code** [comment]
This issues list is for reporting problems with the documentation. Your question doesn't seem to be about the documentation.

There are alternative resources available if you need help debugging your application. I notice that you've already asked this same question on Discord, so hopefully someone on there will be able to help you.

**Comment by tjl-cmd** [comment]
这个应该是框架内部的问题吧
