### ISSUE TITLE
This expression is not constructable.

### ISSUE THREAD

**Issue by myogeshverma** [vuejs/docs-next#826]
Using Vue 3 + typescript + GraphQl

<img width="467" alt="Screenshot 2021-01-27 at 4 15 20 PM" src="https://user-images.githubusercontent.com/19171423/105980448-e198c080-60ba-11eb-8246-a40e192d0c35.png">
<img width="566" alt="Screenshot 2021-01-27 at 4 15 10 PM" src="https://user-images.githubusercontent.com/19171423/105980460-e52c4780-60ba-11eb-9bf4-0cfedcbfe69b.png">

Package.json
{
  "name": "APPNAME",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "test:e2e": "vue-cli-service test:e2e",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "eslint-plugin-graphql": "^4.0.0",
    "register-service-worker": "^1.7.1",
    "vue": "^3.0.0",
    "vue-apollo": "^3.0.0-beta.11",
    "vue-class-component": "^8.0.0-0",
    "vue-router": "^4.0.0-0",
    "vue-template-compiler": "^2.6.12",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "@graphql-eslint/eslint-plugin": "^0.7.2",
    "@types/jest": "^24.0.19",
    "@typescript-eslint/eslint-plugin": "^4.9.1",
    "@typescript-eslint/parser": "^4.9.1",
    "@vue/cli-plugin-babel": "~5.0.0-alpha.3",
    "@vue/cli-plugin-e2e-cypress": "~5.0.0-alpha.3",
    "@vue/cli-plugin-eslint": "~5.0.0-alpha.3",
    "@vue/cli-plugin-pwa": "~5.0.0-alpha.3",
    "@vue/cli-plugin-router": "~5.0.0-alpha.3",
    "@vue/cli-plugin-typescript": "~5.0.0-alpha.3",
    "@vue/cli-plugin-unit-jest": "~5.0.0-alpha.3",
    "@vue/cli-plugin-vuex": "~5.0.0-alpha.3",
    "@vue/cli-service": "~5.0.0-alpha.3",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-airbnb": "^5.3.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "@vue/test-utils": "^2.0.0-0",
    "eslint": "^7.15.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-vue": "^7.2.0",
    "graphql-tag": "^2.9.0",
    "typescript": "~4.1.2",
    "vue-cli-plugin-apollo": "^0.22.2",
    "vue-jest": "^5.0.0-0"
  }
}

**Comment by NataliaTepluhina** [comment]
When creating an application with Vue 3, you should use [createApp](https://v3.vuejs.org/api/global-api.html#createapp) method, not `new Vue()`

Also, docs repository is not a correct place to ask for code help, please check [VueLand Discord](http://chat.vuejs.org/) for this.
