### ISSUE TITLE
Codepen error

### ISSUE THREAD

**Issue by Vac1911** [vuejs/docs-next#827]
This imbedded codepen is producing an error.

Codepen: https://codepen.io/team/Vue/pen/76e344bf057bd58b5936bba260b787a8
Docs Location: https://v3.vuejs.org/guide/transitions-enterleave.html#cp_embed_76e344bf057bd58b5936bba260b787a8

![image](https://user-images.githubusercontent.com/45333542/106291962-44549e00-621a-11eb-95da-ed92b83c03ef.png)

Google Chrome - Version 88.0.4324.104 (Official Build) (64-bit)

**Comment by skirtles-code** [comment]
I've done some preliminary investigation.

It seems this worked in 3.0.3 but is broken in 3.0.4 and 3.0.5.

Wrapping the `<slot>` in another element, such as a `<div>`, and moving the `v-if` to that element fixes it. However, that shouldn't be necessary.

`filterSingleRoot` is being passed `null` for its `children` argument. This comes from `vnode.children` in `getChildRoot` and the node that fails is the `<img>`. It isn't immediately clear to me why it needs to check the children of the `<img>` but either it needs to handle the `null` or the children need to be `[]`.

I experimented a bit and it seems that the same problem can be reproduced with any empty element, it doesn't have to be an `<img>`. A empty `<div>` gave the same error. Putting any content in the `<div>` was enough for the error to go away.

**Comment by NataliaTepluhina** [comment]
@Vac1911 thank you for reporting this! I've fixed a codepen with @skirtles-code recommended solution as a workaround.

@skirtles-code do you think this is rather a bug than a feature? Should we open an issue on core repo?

**Comment by skirtles-code** [comment]
Done.

Closing this for now but we should probably switch it back once the bug is fixed.
