### ISSUE TITLE
[Suggestion] Add 'Structural Guidelines' guide

### ISSUE THREAD

**Issue by xianghongai** [vuejs/docs-next#843]
Can we add a document about organization project directory and file structure?

---

- [File Structure – React](https://reactjs.org/docs/faq-structure.html)
- [Overall structural guidelines - Angular](https://angular.io/guide/styleguide#overall-structural-guidelines)

**Comment by NataliaTepluhina** [comment]
I would like to notice that both guides start with `does not have opinions` and `opinionated` so they are very vague. On Vue projects, file structure is usually inherited either from Vue CLI or Nuxt so I am not sure it requires documentation on the main guide.

However, we might rethink this question if we decide to have two 'paths' in the docs - for those who start with CDN script and for those who start with ESM (the latter is more likely to have a file structure explanation).

Closing an issue for now.
