### ISSUE TITLE
please document Class-Style Vue Components

### ISSUE THREAD

**Issue by softboy99** [vuejs/docs-next#854]
Hi,
In vue2.x, in chapter for "TypeScrpirt Support", there are docuementation about "Class-Style Vue Components"; In vue3, no anything about this.  Is it abandoned api? if so, please also give something description. What's the status of [https://github.com/vuejs/rfcs/blob/class-api/active-rfcs/0000-class-api.md](url). Not everyone is clear. Thanks.

**Comment by NataliaTepluhina** [comment]
@softboy99 Vue Class API proposal [has been dropped](https://github.com/vuejs/rfcs/pull/17#issuecomment-494242121) in favor of the Composition API. If you prefer to use `vue-class-component` library, please read https://github.com/vuejs/vue-class-component/issues/406

However, this is not a core API and it's still under development so it's not mentioned in the documentation.
