### ISSUE TITLE
Custom directive in render function

### ISSUE THREAD

**Issue by shameleo** [vuejs/docs-next#855]
In Vue 2 directives should be passes to `directives` property of VNode data object.
In Vue 3 data object has flat structure, but no examples of how to use directives.
Tried this: 
```js
import { h } from 'vue';
import { focus } from '@scripts/directives.js';

export default {
    directives: {
        focus
    },
    render: () => h('input', {
        type: 'text',
        vFocus: true
    });
}
```
and many other suggestions without any success.

**Comment by NataliaTepluhina** [comment]
@shameleo does this resolve your querstion? https://v3.vuejs.org/api/global-api.html#withdirectives

**Comment by shameleo** [comment]
Oh, I missed that somehow. Thank you.
But it would be nice to have some link or mentioning here:  https://v3.vuejs.org/guide/render-function.html

**Comment by NataliaTepluhina** [comment]
@shameleo yep, I agree that this should be also shown in the guide somewhere 👍🏻
