### ISSUE TITLE
Template compilation example not working

### ISSUE THREAD

**Issue by kospl** [vuejs/docs-next#867]
URL: https://v3.vuejs.org/guide/render-function.html#template-compilation

![image](https://user-images.githubusercontent.com/26386660/108637683-4b2aa580-7494-11eb-9be3-39353a935f13.png)

Here's v2 version of example, for the reference:
![image](https://user-images.githubusercontent.com/26386660/108637722-76ad9000-7494-11eb-94de-8cf1b7f68080.png)

**Comment by skirtles-code** [comment]
I believe this is because you're accessing the page using an incognito window.

I don't think we can fix this from the docs but perhaps the template compiler page could be tweaked to allow it to work without `localStorage`.

**Comment by kospl** [comment]
@skirtles-code yeah, seems Google went all wrong with handling web storage in incognito mode https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API#private_browsing_incognito_modes

btw works in Edge when in incognito mode.
