### ISSUE TITLE
Non-Prop Attributes   举的例子  <input type="datetime" />  应该替换为  datetime-local

### ISSUE THREAD

**Issue by Ryokutouto** [vuejs/docs-next#868]

**Comment by skirtles-code** [comment]
For anyone else who was wondering, I believe the suggestion here it to change `type="datetime"` to `type="datetime-local"` in the examples on this page:

https://v3.vuejs.org/guide/component-attrs.html

See also: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime
