### ISSUE TITLE
Line numbers in codes example not lining up in Chrome

### ISSUE THREAD

**Issue by davewsmith** [vuejs/docs-next#915]
In Chrome 88.0.4324.182, line numbers in code examples don't line up with code. E.g., https://v3.vuejs.org/guide/computed.html

In Firefox 66.03, they do.

The .line-style class declaration in https://github.com/vuejs/docs-next/blob/e5f2fd1861afa15406f6f79c27b4ced9112b0ba0/src/.vuepress/theme/styles/code.styl specifies `font-size: 0.85em`. Setting this to `0.80em` using the Chrome developer tools works to get the line numbers lined up in Chrome (and breaks Firefox). Fun, eh?

   `

**Comment by davewsmith** [comment]
Adding that it appears that `line-height` is being calculated inconsistently between the two browsers. 19.04px in Chrome, 19.0333px in Firefox. Calculated `font-size` is 13.6 in both cases.

(Ubuntu 18.04)

**Comment by skirtles-code** [comment]
See https://github.com/vuejs/vuepress/issues/2691, which was originally reported here but was migrated to the VuePress repo.

**Comment by NataliaTepluhina** [comment]
Closing an issue here as it's rather a platform bug than a project bug
