### ISSUE TITLE
vue add typescript eslint error with node.js ver 15.11.0

### ISSUE THREAD

**Issue by capegreg** [vuejs/docs-next#926]
**vue add typescript** failed on node.js version 15.11.0. 
Had to downgrade node.js. Successful on node.js to v14.16.0

![Screenshot 2021-03-04 115520](https://user-images.githubusercontent.com/1051118/109999795-9a68a580-7ce0-11eb-9857-c9d5d904835a.png)

**Comment by skirtles-code** [comment]
Thanks for the report but I don't think this is the right issues list for that problem. This list is for problems with the Vue 3 documentation. You probably need to report that problem as an issue in the [Vue CLI repo](https://github.com/vuejs/vue-cli).

You may also need to include information about what you did prior to running `vue add typescript`. For example, is the problem reproducible with a newly created project using the Vue 3 preset?
