### ISSUE TITLE
Very difficult to search elements

### ISSUE THREAD

**Issue by blizardinka** [vuejs/docs-next#929]
<img width="494" alt="Screenshot 2021-03-05 at 16 52 10" src="https://user-images.githubusercontent.com/17678627/110140712-a9c91b00-7dd4-11eb-864a-e985ec7bfe05.png">
<img width="458" alt="Screenshot 2021-03-05 at 16 52 32" src="https://user-images.githubusercontent.com/17678627/110140738-b3eb1980-7dd4-11eb-9193-a4490202afcf.png">
Hi everyone! It is inconvenient to search for the required element while studying the documentation. I compare the study of documentation / specification html and vue. For example, let's look at html first and then vue. I want to learn a head or body element, I go to "content", press cmd + f and enter "body" or "head" and start learning. Now the example on the vue site. I want to study the "v-on: click (@click)" element, I open the "Docs" tab and cannot figure out how to determine that at least the first mention of "v-on: click (@click)" is located in
"Template Syntax -> Directives -> Arguments". As a person who has just started learning vue, it is hard for me to search. What do you think about this?

**Comment by LinusBorg** [comment]
A better place to look up specific APIs would be the API documentation, I would say? There, it's explicitly listed under "Directives".

![image](https://user-images.githubusercontent.com/1444526/110216253-64791c00-7eae-11eb-9cf3-2634e3a47cbb.png)

There's also a dedicated search function:

![image](https://user-images.githubusercontent.com/1444526/110216270-7c50a000-7eae-11eb-8dc4-c25603f2f230.png)

Yes, having the whole documentation on one page has the advantage of being able to search with the browsers find feature, but that's a nightmare to maintain.
