### ISSUE TITLE
Outdated timeline for stabilization of Supporting Libraries

### ISSUE THREAD

**Issue by agersant** [vuejs/docs-next#931]
Hello and thank you for working on Vue!

I have been waiting for supporting libraries to be stable before migrating my app to Vue 3. The [documentation](https://v3.vuejs.org/guide/migration/introduction.html#supporting-libraries) announces plans to stabilize them by end of 2020, but that did not happen. Would it be possible to have an updated ETA for this change?

> All of our official libraries and tools now support Vue 3, but most of them are still in beta status and distributed under the next dist tag on npm. We are planning to stabilize and switch all projects to use the latest dist tag by end of 2020.

Thanks in advance and keep up the good work <3

**Comment by skirtles-code** [comment]
That paragraph does need updating.

Most of the official libraries are listed below that paragraph and the latest versions are shown. Vue Router and Vuex both have compatible, stable releases, as do `@vue/babel-plugin-jsx`, `eslint-plugin-vue` and `vue-loader`. A handful of other libraries are in RC or beta, though that should only be a problem if you're using them.

The label switch from `next` to `latest` needs to happen eventually but it would need to happen across the board to keep all versions compatible. The current label shouldn't be taken as a reflection on whether individual libraries are ready to be used. Even once the label is switched there will still be third-party libraries within the ecosystem that are not compatible with Vue 3. I suggest checking the individual libraries you need to see whether they have stable versions.
