### ISSUE TITLE
feature wanted: auto open translation docs with the current url pathname

### ISSUE THREAD

**Issue by xgqfrms** [vuejs/docs-next#932]
# feature wanted

> auto open translation docs with the current url pathname

## current

> click the translation zh-Hans link, just goto the home page

https://v3.vuejs.org/guide/composition-api-setup.html#props

`=>`

https://v3.cn.vuejs.org/

## wanted

> click the translation zh-Hans link, goto the page with the current url pathname

https://v3.vuejs.org/guide/composition-api-setup.html#props

`=>`

https://v3.cn.vuejs.org/guide/composition-api-setup.html#props

## try failed

https://github.com/vuejs/docs-next/blob/master/src/.vuepress/config.js#L418

```js
          {
            text: '中文',
            link: 'https://v3.cn.vuejs.org/'
          }
```

```js
          {
            text: '中文',
            link: `https://v3.cn.vuejs.org${window?.location?.pathname}`,
          }
```

**Comment by skirtles-code** [comment]
I understand why this would be desirable but I'm not sure whether it would be practical. New pages are added to the documentation all the time and there is inevitably a delay before those pages are added to the translations.

**Comment by skirtles-code** [comment]
I'm going to close this for now. We can reopen it if someone can suggest a viable strategy for handling new pages that aren't yet in the translations.
