### ISSUE TITLE
Warning missing required prop when using camelCase

### ISSUE THREAD

**Issue by pmiguelmartins** [vuejs/docs-next#967]
**Version**

3.0.8

**Reproduction link**

Vue 3.x reproduce link: [https://jsfiddle.net/pmiguelmartins/eq5hL2ty/10/](https://jsfiddle.net/pmiguelmartins/eq5hL2ty/10/)

**Steps to reproduce**

Define a props in a component, with required: true 
Use this component and pass the prop

**What is expected?**

No errors

**What is actually happening?**

Gives an warning in console.

**Comment by skirtles-code** [comment]
Thanks for the report but I believe this is a bug in 3.0.8 rather than a docs issue.

See https://github.com/vuejs/vue-next/issues/3495

**Comment by pmiguelmartins** [comment]
> Thanks for the report but I believe this is a bug in 3.0.8 rather than a docs issue.
> 
> See [vuejs/vue-next#3495](https://github.com/vuejs/vue-next/issues/3495)

Sorry ...

thanks for reporting in right place

Pedro Martins
