### ISSUE TITLE
ThreeJS component working in VueJS 2 but not 3

### ISSUE THREAD

**Issue by spiritzx** [vuejs/docs-next#994]
I'm upgrading my app to VueJS 3. I read that you could keep the same components. But I have an error in the console now, although I didn't change anything. Here is my error:

```
init() {
...
this.scene = new three.Scene();
....
this.camera = camera;
...
}
render() {
 this.render.render(this.scene, this.camera);
}

```

```
three.module.js?5a89:24471 Uncaught TypeError: 'get' on proxy: property 'modelViewMatrix' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Matrix4>' but got '[object Object]')
    at renderObject (three.module.js?5a89:24471)
    at renderObjects (three.module.js?5a89:24458)
    at Proxy.WebGLRenderer.render (three.module.js?5a89:24258)
    at animate (HelloWorld.vue?fdab:192)
```

**Comment by skirtles-code** [comment]
> I read that you could keep the same components.

That isn't necessarily true. If you read that anywhere in the official documentation then please let us know so we can correct it.

A lot of components can be migrated to Vue 3 without any changes at all, others require only minimal changes. However, it depends exactly what features a component is using, and in some, rare cases a component may need a major overhaul. The migration guide outlines most of these changes.

At first glance, it would appear to be a problem with the new proxy-based reactivity system interacting with an object from Three.js. The usual recommendation is to use only 'plain' JavaScript objects for reactive data. There are various other ways you might address this, e.g. `markRaw`.

If you need help debugging and fixing this problem I suggest asking on the [Vue Land Discord](https://chat.vuejs.org/).

I'm going to close this issue as it doesn't appear to be a documentation problem.
